//
//  ModelDataFunc.swift
//  JWordDev
//
//  Created by 강 on 4/30/25.
//

import SwiftUI
import SwiftData

func ModelDataFuncN2 (into context: ModelContext){
    let JPWordsN2 = [
        JWordModel(kanji: "暴れる", yomigana: "あばれる", meaning: "난폭하게 굴다, 날뛰다"),
        JWordModel(kanji: "溢れる", yomigana: "あふれる", meaning: "넘치다, 흘러넘치다"),
        JWordModel(kanji: "愛着", yomigana: "あいちゃく", meaning: "애착"),
        JWordModel(kanji: "合間", yomigana: "あいま", meaning: "틈, 짬"),
        JWordModel(kanji: "曖昧", yomigana: "あいまい", meaning: "애매함"),
        JWordModel(kanji: "愛らしい", yomigana: "あいらしい", meaning: "귀엽다, 사랑스럽다"),
        JWordModel(kanji: "愛社", yomigana: "あいしゃ", meaning: "회사에 대한 애정"),
        JWordModel(kanji: "相性", yomigana: "あいしょう", meaning: "궁합, 궁합이 맞음"),
        JWordModel(kanji: "相次いで", yomigana: "あいついで", meaning: "잇따라, 연이어"),
        JWordModel(kanji: "愛用", yomigana: "あいよう", meaning: "애용"),
        JWordModel(kanji: "合図", yomigana: "あいず", meaning: "신호"),
        JWordModel(kanji: "相当", yomigana: "そうとう", meaning: "상당"),
        JWordModel(kanji: "相変わらず", yomigana: "あいかわらず", meaning: "여전히"),
        JWordModel(kanji: "明け方", yomigana: "あけがた", meaning: "새벽녘"),
        JWordModel(kanji: "青白い", yomigana: "あおじろい", meaning: "파랗게 질리다"),
        JWordModel(kanji: "足跡", yomigana: "あしあと", meaning: "발자국"),
        JWordModel(kanji: "足元", yomigana: "あしもと", meaning: "발밑, 발치"),
        JWordModel(kanji: "味わう", yomigana: "あじわう", meaning: "맛보다, 음미하다"),
        JWordModel(kanji: "預かる", yomigana: "あずかる", meaning: "맡다"),
        JWordModel(kanji: "預ける", yomigana: "あずける", meaning: "맡기다"),
        JWordModel(kanji: "与える", yomigana: "あたえる", meaning: "주다, 부여하다"),
        JWordModel(kanji: "暖まる", yomigana: "あたたまる", meaning: "따뜻해지다"),
        JWordModel(kanji: "暖める", yomigana: "あたためる", meaning: "따뜻하게 하다"),
        JWordModel(kanji: "当たり前", yomigana: "あたりまえ", meaning: "당연함"),
        JWordModel(kanji: "扱う", yomigana: "あつかう", meaning: "다루다"),
        JWordModel(kanji: "集まり", yomigana: "あつまり", meaning: "모임"),
        JWordModel(kanji: "当てはまる", yomigana: "あてはまる", meaning: "해당되다"),
        JWordModel(kanji: "当てはめる", yomigana: "あてはめる", meaning: "적용하다"),
        JWordModel(kanji: "暴く", yomigana: "あばく", meaning: "폭로하다, 들추다"),
        JWordModel(kanji: "浴びる", yomigana: "あびる", meaning: "JWordModel(물을) 뒤집어쓰다"),
        JWordModel(kanji: "余る", yomigana: "あまる", meaning: "남다"),
        JWordModel(kanji: "編む", yomigana: "あむ", meaning: "짜다, 뜨다"),
        JWordModel(kanji: "誤る", yomigana: "あやまる", meaning: "실수하다, 잘못하다"),
        JWordModel(kanji: "争う", yomigana: "あらそう", meaning: "다투다, 싸우다"),
        JWordModel(kanji: "改める", yomigana: "あらためる", meaning: "고치다, 바로잡다"),
        JWordModel(kanji: "現す", yomigana: "あらわす", meaning: "나타내다, 드러내다"),
        JWordModel(kanji: "表す", yomigana: "あらわす", meaning: "표현하다, 나타내다"),
        JWordModel(kanji: "現れる", yomigana: "あらわれる", meaning: "나타나다, 드러나다"),
        JWordModel(kanji: "表れる", yomigana: "あらわれる", meaning: "나타나다, 드러나다"),
        JWordModel(kanji: "有難い", yomigana: "ありがたい", meaning: "고맙다, 감사하다"),
        JWordModel(kanji: "在り方", yomigana: "ありかた", meaning: "있어야 할 상태, 본연의 자세"),
        JWordModel(kanji: "有り得る", yomigana: "ありうる", meaning: "있을 수 있다"),
        JWordModel(kanji: "有り難い", yomigana: "ありがたい", meaning: "고맙다, 감사하다"),
        JWordModel(kanji: "歩み", yomigana: "あゆみ", meaning: "걸음, 진행"),
        JWordModel(kanji: "歩む", yomigana: "あゆむ", meaning: "걷다, 나아가다"),
        JWordModel(kanji: "荒い", yomigana: "あらい", meaning: "거칠다"),
        JWordModel(kanji: "争い", yomigana: "あらそい", meaning: "다툼, 싸움"),
        JWordModel(kanji: "嵐", yomigana: "あらし", meaning: "폭풍"),
        JWordModel(kanji: "改まる", yomigana: "あらたまる", meaning: "고쳐지다, 새로워지다"),
        JWordModel(kanji: "改めて", yomigana: "あらためて", meaning: "다시, 새삼"),
        JWordModel(kanji: "表", yomigana: "おもて", meaning: "표면, 겉"),
        JWordModel(kanji: "案外", yomigana: "あんがい", meaning: "뜻밖에, 의외로"),
        JWordModel(kanji: "暗記", yomigana: "あんき", meaning: "암기"),
        JWordModel(kanji: "安定", yomigana: "あんてい", meaning: "안정"),
        JWordModel(kanji: "委員", yomigana: "いいん", meaning: "위원"),
        JWordModel(kanji: "意外", yomigana: "いがい", meaning: "의외"),
        JWordModel(kanji: "意義", yomigana: "いぎ", meaning: "의의, 의미"),
        JWordModel(kanji: "意志", yomigana: "いし", meaning: "의지"),
        JWordModel(kanji: "意思", yomigana: "いし", meaning: "의사, 의지"),
        JWordModel(kanji: "意識", yomigana: "いしき", meaning: "의식"),
        JWordModel(kanji: "維持", yomigana: "いじ", meaning: "유지"),
        JWordModel(kanji: "異常", yomigana: "いじょう", meaning: "이상, 비정상"),
        JWordModel(kanji: "意地悪", yomigana: "いじわる", meaning: "심술궂음, 짓궂음"),
        JWordModel(kanji: "移住", yomigana: "いじゅう", meaning: "이주"),
        JWordModel(kanji: "依然", yomigana: "いぜん", meaning: "여전히"),
        JWordModel(kanji: "以前", yomigana: "いぜん", meaning: "이전"),
        JWordModel(kanji: "至る", yomigana: "いたる", meaning: "이르다, 도달하다"),
        JWordModel(kanji: "一応", yomigana: "いちおう", meaning: "일단, 일응"),
        JWordModel(kanji: "一段と", yomigana: "いちだんと", meaning: "한층 더"),
        JWordModel(kanji: "一度に", yomigana: "いちどに", meaning: "한꺼번에"),
        JWordModel(kanji: "一方", yomigana: "いっぽう", meaning: "한편, 한쪽"),
        JWordModel(kanji: "一流", yomigana: "いちりゅう", meaning: "일류"),
        JWordModel(kanji: "一致", yomigana: "いっち", meaning: "일치"),
        JWordModel(kanji: "一致する", yomigana: "いっちする", meaning: "일치하다"),
        JWordModel(kanji: "一種", yomigana: "いっしゅ", meaning: "일종"),
        JWordModel(kanji: "一瞬", yomigana: "いっしゅん", meaning: "순간"),
        JWordModel(kanji: "一生", yomigana: "いっしょう", meaning: "일생, 평생"),
        JWordModel(kanji: "一斉に", yomigana: "いっせいに", meaning: "일제히"),
        JWordModel(kanji: "一層", yomigana: "いっそう", meaning: "한층 더"),
        JWordModel(kanji: "一体", yomigana: "いったい", meaning: "도대체"),
        JWordModel(kanji: "一致点", yomigana: "いっちてん", meaning: "일치점"),
        JWordModel(kanji: "移動", yomigana: "いどう", meaning: "이동"),
        JWordModel(kanji: "移転", yomigana: "いてん", meaning: "이전, 이동"),
        JWordModel(kanji: "移入", yomigana: "いにゅう", meaning: "이입, 유입"),
        JWordModel(kanji: "移民", yomigana: "いみん", meaning: "이민"),
        JWordModel(kanji: "違反", yomigana: "いはん", meaning: "위반"),
        JWordModel(kanji: "違法", yomigana: "いほう", meaning: "위법"),
        JWordModel(kanji: "違和感", yomigana: "いわかん", meaning: "이질감"),
        JWordModel(kanji: "引用", yomigana: "いんよう", meaning: "인용"),
        JWordModel(kanji: "飲食", yomigana: "いんしょく", meaning: "음식, 음식물"),
        JWordModel(kanji: "引力", yomigana: "いんりょく", meaning: "인력, 끄는 힘"),
        JWordModel(kanji: "陰", yomigana: "かげ", meaning: "그늘, 그림자"),
        JWordModel(kanji: "陰気", yomigana: "いんき", meaning: "음침함"),
        JWordModel(kanji: "運河", yomigana: "うんが", meaning: "운하"),
        JWordModel(kanji: "運送", yomigana: "うんそう", meaning: "운송"),
        JWordModel(kanji: "運賃", yomigana: "うんちん", meaning: "운임, 요금"),
        JWordModel(kanji: "運搬", yomigana: "うんぱん", meaning: "운반"),
        JWordModel(kanji: "運用", yomigana: "うんよう", meaning: "운용"),
        JWordModel(kanji: "映像", yomigana: "えいぞう", meaning: "영상"),
        JWordModel(kanji: "衛星", yomigana: "えいせい", meaning: "위성"),
        JWordModel(kanji: "営業", yomigana: "えいぎょう", meaning: "영업"),
        JWordModel(kanji: "影響", yomigana: "えいきょう", meaning: "영향"),
        JWordModel(kanji: "映る", yomigana: "うつる", meaning: "비치다, 비춰지다"),
        JWordModel(kanji: "映す", yomigana: "うつす", meaning: "비추다, 투영하다"),
        JWordModel(kanji: "得る", yomigana: "える", meaning: "얻다"),
        JWordModel(kanji: "延長", yomigana: "えんちょう", meaning: "연장"),
        JWordModel(kanji: "延期", yomigana: "えんき", meaning: "연기"),
        JWordModel(kanji: "沿う", yomigana: "そう", meaning: "따르다, 따라가다"),
        JWordModel(kanji: "援助", yomigana: "えんじょ", meaning: "원조, 지원"),
        JWordModel(kanji: "演技", yomigana: "えんぎ", meaning: "연기JWordModel(배우)"),
        JWordModel(kanji: "演習", yomigana: "えんしゅう", meaning: "연습"),
        JWordModel(kanji: "演奏", yomigana: "えんそう", meaning: "연주"),
        JWordModel(kanji: "演出", yomigana: "えんしゅつ", meaning: "연출"),
        JWordModel(kanji: "演説", yomigana: "えんぜつ", meaning: "연설"),
        JWordModel(kanji: "遠慮", yomigana: "えんりょ", meaning: "사양, 삼감"),
        JWordModel(kanji: "縁", yomigana: "えん", meaning: "인연, 연고"),
        JWordModel(kanji: "応援", yomigana: "おうえん", meaning: "응원"),
        JWordModel(kanji: "応じる", yomigana: "おうじる", meaning: "응하다, 따르다"),
        JWordModel(kanji: "応対", yomigana: "おうたい", meaning: "응대"),
        JWordModel(kanji: "応用", yomigana: "おうよう", meaning: "응용"),
        JWordModel(kanji: "往復", yomigana: "おうふく", meaning: "왕복"),
        JWordModel(kanji: "横断", yomigana: "おうだん", meaning: "횡단"),
        JWordModel(kanji: "王女", yomigana: "おうじょ", meaning: "왕녀, 공주"),
        JWordModel(kanji: "王子", yomigana: "おうじ", meaning: "왕자"),
        JWordModel(kanji: "王様", yomigana: "おうさま", meaning: "임금님"),
        JWordModel(kanji: "大いに", yomigana: "おおいに", meaning: "크게, 매우"),
        JWordModel(kanji: "大家", yomigana: "おおや", meaning: "집주인"),
        JWordModel(kanji: "大通り", yomigana: "おおどおり", meaning: "큰길, 대로"),
        JWordModel(kanji: "大幅", yomigana: "おおはば", meaning: "대폭"),
        JWordModel(kanji: "大部分", yomigana: "おおぶぶん", meaning: "대부분"),
        JWordModel(kanji: "丘", yomigana: "おか", meaning: "언덕"),
        JWordModel(kanji: "沖", yomigana: "おき", meaning: "먼 바다"),
        JWordModel(kanji: "屋外", yomigana: "おくがい", meaning: "옥외, 실외"),
        JWordModel(kanji: "奥", yomigana: "おく", meaning: "안, 깊숙한 곳"),
        JWordModel(kanji: "贈る", yomigana: "おくる", meaning: "보내다, 선물하다"),
        JWordModel(kanji: "怠る", yomigana: "おこたる", meaning: "게을리하다, 소홀히 하다"),
        JWordModel(kanji: "起こる", yomigana: "おこる", meaning: "일어나다, 발생하다"),
        JWordModel(kanji: "抑える", yomigana: "おさえる", meaning: "억누르다, 억제하다"),
        JWordModel(kanji: "納める", yomigana: "おさめる", meaning: "납부하다, 수납하다"),
        JWordModel(kanji: "教わる", yomigana: "おそわる", meaning: "가르침을 받다"),
        JWordModel(kanji: "恐れる", yomigana: "おそれる", meaning: "두려워하다"),
        JWordModel(kanji: "恐ろしい", yomigana: "おそろしい", meaning: "무섭다"),
        JWordModel(kanji: "お互い", yomigana: "おたがい", meaning: "서로"),
        JWordModel(kanji: "お手洗い", yomigana: "おてあらい", meaning: "화장실"),
        JWordModel(kanji: "劣る", yomigana: "おとる", meaning: "뒤떨어지다, 못하다"),
        JWordModel(kanji: "驚かす", yomigana: "おどろかす", meaning: "놀라게 하다"),
        JWordModel(kanji: "驚き", yomigana: "おどろき", meaning: "놀람"),
        JWordModel(kanji: "及ぼす", yomigana: "およぼす", meaning: "미치게 하다"),
        JWordModel(kanji: "及ぶ", yomigana: "およぶ", meaning: "미치다, 이르다"),
        JWordModel(kanji: "恩", yomigana: "おん", meaning: "은혜"),
        JWordModel(kanji: "温暖", yomigana: "おんだん", meaning: "온난"),
        JWordModel(kanji: "温度", yomigana: "おんど", meaning: "온도"),
        JWordModel(kanji: "可決", yomigana: "かけつ", meaning: "가결"),
        JWordModel(kanji: "会計", yomigana: "かいけい", meaning: "회계"),
        JWordModel(kanji: "会合", yomigana: "かいごう", meaning: "회합, 모임"),
        JWordModel(kanji: "解決", yomigana: "かいけつ", meaning: "해결"),
        JWordModel(kanji: "解釈", yomigana: "かいしゃく", meaning: "해석"),
        JWordModel(kanji: "改正", yomigana: "かいせい", meaning: "개정"),
        JWordModel(kanji: "改造", yomigana: "かいぞう", meaning: "개조"),
        JWordModel(kanji: "回転", yomigana: "かいてん", meaning: "회전"),
        JWordModel(kanji: "快適", yomigana: "かいてき", meaning: "쾌적함"),
        JWordModel(kanji: "回復", yomigana: "かいふく", meaning: "회복"),
        JWordModel(kanji: "替える", yomigana: "かえる", meaning: "바꾸다, 교체하다"),
        JWordModel(kanji: "抱える", yomigana: "かかえる", meaning: "안다, 끌어안다"),
        JWordModel(kanji: "掲げる", yomigana: "かかげる", meaning: "내걸다, 내세우다"),
        JWordModel(kanji: "関わる", yomigana: "かかわる", meaning: "관계되다, 관련되다"),
        JWordModel(kanji: "係", yomigana: "かかり", meaning: "담당, 담당자"),
        JWordModel(kanji: "掛かる", yomigana: "かかる", meaning: "걸리다, 들다"),
        JWordModel(kanji: "掛ける", yomigana: "かける", meaning: "걸다, JWordModel(시간/돈) 걸리다"),
        JWordModel(kanji: "飾り", yomigana: "かざり", meaning: "장식"),
        JWordModel(kanji: "飾る", yomigana: "かざる", meaning: "장식하다"),
        JWordModel(kanji: "数える", yomigana: "かぞえる", meaning: "세다, 계산하다"),
        JWordModel(kanji: "片付ける", yomigana: "かたづける", meaning: "정리하다, 치우다"),
        JWordModel(kanji: "傾く", yomigana: "かたむく", meaning: "기울다"),
        JWordModel(kanji: "傾ける", yomigana: "かたむける", meaning: "기울이다"),
        JWordModel(kanji: "語る", yomigana: "かたる", meaning: "말하다, 이야기하다"),
        JWordModel(kanji: "勝ち", yomigana: "かち", meaning: "이김, 승리"),
        JWordModel(kanji: "価値", yomigana: "かち", meaning: "가치"),
        JWordModel(kanji: "活気", yomigana: "かっき", meaning: "활기"),
        JWordModel(kanji: "学期", yomigana: "がっき", meaning: "학기"),
        JWordModel(kanji: "学習", yomigana: "がくしゅう", meaning: "학습"),
        JWordModel(kanji: "学者", yomigana: "がくしゃ", meaning: "학자"),
        JWordModel(kanji: "学問", yomigana: "がくもん", meaning: "학문"),
        JWordModel(kanji: "学力", yomigana: "がくりょく", meaning: "학력"),
        JWordModel(kanji: "確実", yomigana: "かくじつ", meaning: "확실함"),
        JWordModel(kanji: "確認", yomigana: "かくにん", meaning: "확인"),
        JWordModel(kanji: "拡大", yomigana: "かくだい", meaning: "확대"),
        JWordModel(kanji: "拡張", yomigana: "かくちょう", meaning: "확장"),
        JWordModel(kanji: "隠す", yomigana: "かくす", meaning: "숨기다"),
        JWordModel(kanji: "隠れる", yomigana: "かくれる", meaning: "숨다"),
        JWordModel(kanji: "加減", yomigana: "かげん", meaning: "가감, 조절"),
        JWordModel(kanji: "掛け算", yomigana: "かけざん", meaning: "곱셈"),
        JWordModel(kanji: "火災", yomigana: "かさい", meaning: "화재"),
        JWordModel(kanji: "貸し出す", yomigana: "かしだす", meaning: "대출하다"),
        JWordModel(kanji: "貸す", yomigana: "かす", meaning: "빌려주다"),
        JWordModel(kanji: "稼ぐ", yomigana: "かせぐ", meaning: "벌다, 돈을 벌다"),
        JWordModel(kanji: "数", yomigana: "かず", meaning: "수, 숫자"),
        JWordModel(kanji: "型", yomigana: "かた", meaning: "형, 타입"),
        JWordModel(kanji: "片道", yomigana: "かたみち", meaning: "편도"),
        JWordModel(kanji: "勝つ", yomigana: "かつ", meaning: "이기다"),
        JWordModel(kanji: "活用", yomigana: "かつよう", meaning: "활용"),
        JWordModel(kanji: "必ずしも", yomigana: "かならずしも", meaning: "반드시 ~인 것은 아니다"),
        JWordModel(kanji: "要る", yomigana: "いる", meaning: "필요하다"),
        JWordModel(kanji: "構う", yomigana: "かまう", meaning: "상관하다, 신경 쓰다"),
        JWordModel(kanji: "構える", yomigana: "かまえる", meaning: "구축하다, 자세를 취하다"),
        JWordModel(kanji: "噛む", yomigana: "かむ", meaning: "씹다"),
        JWordModel(kanji: "通う", yomigana: "かよう", meaning: "다니다"),
        JWordModel(kanji: "枯れる", yomigana: "かれる", meaning: "마르다, 시들다"),
        JWordModel(kanji: "彼", yomigana: "かれ", meaning: "그, 그 사람"),
        JWordModel(kanji: "彼女", yomigana: "かのじょ", meaning: "그녀"),
        JWordModel(kanji: "皮", yomigana: "かわ", meaning: "껍질"),
        JWordModel(kanji: "代わり", yomigana: "かわり", meaning: "대신, 대리"),
        JWordModel(kanji: "変わる", yomigana: "かわる", meaning: "변하다"),
        JWordModel(kanji: "換える", yomigana: "かえる", meaning: "바꾸다, 교환하다"),
        JWordModel(kanji: "換わる", yomigana: "かわる", meaning: "바뀌다, 교체되다"),
        JWordModel(kanji: "観光", yomigana: "かんこう", meaning: "관광"),
        JWordModel(kanji: "観察", yomigana: "かんさつ", meaning: "관찰"),
        JWordModel(kanji: "感謝", yomigana: "かんしゃ", meaning: "감사"),
        JWordModel(kanji: "感情", yomigana: "かんじょう", meaning: "감정"),
        JWordModel(kanji: "感じ", yomigana: "かんじ", meaning: "느낌"),
        JWordModel(kanji: "感じる", yomigana: "かんじる", meaning: "느끼다"),
        JWordModel(kanji: "感心", yomigana: "かんしん", meaning: "감탄, 감명"),
        JWordModel(kanji: "関心", yomigana: "かんしん", meaning: "관심"),
        JWordModel(kanji: "感動", yomigana: "かんどう", meaning: "감동"),
        JWordModel(kanji: "完全", yomigana: "かんぜん", meaning: "완전함"),
        JWordModel(kanji: "関係", yomigana: "かんけい", meaning: "관계"),
        JWordModel(kanji: "観客", yomigana: "かんきゃく", meaning: "관객"),
        JWordModel(kanji: "管理", yomigana: "かんり", meaning: "관리"),
        JWordModel(kanji: "関する", yomigana: "かんする", meaning: "~에 관한"),
        JWordModel(kanji: "関東", yomigana: "かんとう", meaning: "간토JWordModel(일본 동부 지방)"),
        JWordModel(kanji: "関西", yomigana: "かんさい", meaning: "간사이JWordModel(일본 서부 지방)"),
        JWordModel(kanji: "観念", yomigana: "かんねん", meaning: "관념, 단념"),
        JWordModel(kanji: "感覚", yomigana: "かんかく", meaning: "감각"),
        JWordModel(kanji: "観測", yomigana: "かんそく", meaning: "관측"),
        JWordModel(kanji: "関節", yomigana: "かんせつ", meaning: "관절"),
        JWordModel(kanji: "乾燥", yomigana: "かんそう", meaning: "건조"),
        JWordModel(kanji: "簡素", yomigana: "かんそ", meaning: "간소"),
        JWordModel(kanji: "簡単", yomigana: "かんたん", meaning: "간단함"),
        JWordModel(kanji: "感動的", yomigana: "かんどうてき", meaning: "감동적"),
        JWordModel(kanji: "監督", yomigana: "かんとく", meaning: "감독"),
        JWordModel(kanji: "管理人", yomigana: "かんりにん", meaning: "관리인"),
        JWordModel(kanji: "気温", yomigana: "きおん", meaning: "기온"),
        JWordModel(kanji: "気圧", yomigana: "きあつ", meaning: "기압"),
        JWordModel(kanji: "機会", yomigana: "きかい", meaning: "기회"),
        JWordModel(kanji: "機械", yomigana: "きかい", meaning: "기계"),
        JWordModel(kanji: "期間", yomigana: "きかん", meaning: "기간"),
        JWordModel(kanji: "機関", yomigana: "きかん", meaning: "기관"),
        JWordModel(kanji: "気球", yomigana: "ききゅう", meaning: "기구JWordModel(열기구 등)"),
        JWordModel(kanji: "危険", yomigana: "きけん", meaning: "위험"),
        JWordModel(kanji: "記号", yomigana: "きごう", meaning: "기호"),
        JWordModel(kanji: "気候", yomigana: "きこう", meaning: "기후"),
        JWordModel(kanji: "聞き手", yomigana: "ききて", meaning: "청자, 듣는 사람"),
        JWordModel(kanji: "記者", yomigana: "きしゃ", meaning: "기자"),
        JWordModel(kanji: "記事", yomigana: "きじ", meaning: "기사JWordModel(신문 등)"),
        JWordModel(kanji: "技術", yomigana: "ぎじゅつ", meaning: "기술"),
        JWordModel(kanji: "記述", yomigana: "きじゅつ", meaning: "기술JWordModel(글로 씀)"),
        JWordModel(kanji: "規則", yomigana: "きそく", meaning: "규칙"),
        JWordModel(kanji: "基礎", yomigana: "きそ", meaning: "기초"),
        JWordModel(kanji: "期待", yomigana: "きたい", meaning: "기대"),
        JWordModel(kanji: "帰宅", yomigana: "きたく", meaning: "귀가"),
        JWordModel(kanji: "記入", yomigana: "きにゅう", meaning: "기입"),
        JWordModel(kanji: "気配", yomigana: "けはい", meaning: "기미, 기색"),
        JWordModel(kanji: "希望", yomigana: "きぼう", meaning: "희망"),
        JWordModel(kanji: "規模", yomigana: "きぼ", meaning: "규모"),
        JWordModel(kanji: "気分", yomigana: "きぶん", meaning: "기분"),
        JWordModel(kanji: "基本", yomigana: "きほん", meaning: "기본"),
        JWordModel(kanji: "記憶", yomigana: "きおく", meaning: "기억"),
        JWordModel(kanji: "客観的", yomigana: "きゃっかんてき", meaning: "객관적"),
        JWordModel(kanji: "休暇", yomigana: "きゅうか", meaning: "휴가"),
        JWordModel(kanji: "休憩", yomigana: "きゅうけい", meaning: "휴식"),
        JWordModel(kanji: "急激", yomigana: "きゅうげき", meaning: "급격함"),
        JWordModel(kanji: "吸収", yomigana: "きゅうしゅう", meaning: "흡수"),
        JWordModel(kanji: "急速", yomigana: "きゅうそく", meaning: "급속"),
        JWordModel(kanji: "給料", yomigana: "きゅうりょう", meaning: "급료, 월급"),
        JWordModel(kanji: "強化", yomigana: "きょうか", meaning: "강화"),
        JWordModel(kanji: "教科書", yomigana: "きょうかしょ", meaning: "교과서"),
        JWordModel(kanji: "共感", yomigana: "きょうかん", meaning: "공감"),
        JWordModel(kanji: "共通", yomigana: "きょうつう", meaning: "공통"),
        JWordModel(kanji: "共同", yomigana: "きょうどう", meaning: "공동"),
        JWordModel(kanji: "協力", yomigana: "きょうりょく", meaning: "협력"),
        JWordModel(kanji: "協調", yomigana: "きょうちょう", meaning: "협조"),
        JWordModel(kanji: "強調", yomigana: "きょうちょう", meaning: "강조"),
        JWordModel(kanji: "教養", yomigana: "きょうよう", meaning: "교양"),
        JWordModel(kanji: "教養的", yomigana: "きょうようてき", meaning: "교양적"),
        JWordModel(kanji: "行儀", yomigana: "ぎょうぎ", meaning: "예의, 행실"),
        JWordModel(kanji: "業績", yomigana: "ぎょうせき", meaning: "업적"),
        JWordModel(kanji: "行列", yomigana: "ぎょうれつ", meaning: "행렬"),
        JWordModel(kanji: "記録", yomigana: "きろく", meaning: "기록"),
        JWordModel(kanji: "議論", yomigana: "ぎろん", meaning: "의논, 토론"),
        JWordModel(kanji: "金庫", yomigana: "きんこ", meaning: "금고"),
        JWordModel(kanji: "金額", yomigana: "きんがく", meaning: "금액"),
        JWordModel(kanji: "金融", yomigana: "きんゆう", meaning: "금융"),
        JWordModel(kanji: "金銭", yomigana: "きんせん", meaning: "금전"),
        JWordModel(kanji: "近代", yomigana: "きんだい", meaning: "근대"),
        JWordModel(kanji: "近年", yomigana: "きんねん", meaning: "근년, 최근"),
        JWordModel(kanji: "近所", yomigana: "きんじょ", meaning: "근처"),
        JWordModel(kanji: "金属", yomigana: "きんぞく", meaning: "금속"),
        JWordModel(kanji: "緊張", yomigana: "きんちょう", meaning: "긴장"),
        JWordModel(kanji: "禁煙", yomigana: "きんえん", meaning: "금연"),
        JWordModel(kanji: "禁止", yomigana: "きんし", meaning: "금지"),
        JWordModel(kanji: "区切る", yomigana: "くぎる", meaning: "구분하다, 끊다"),
        JWordModel(kanji: "苦情", yomigana: "くじょう", meaning: "불평, 항의"),
        JWordModel(kanji: "苦心", yomigana: "くしん", meaning: "고심"),
        JWordModel(kanji: "苦労", yomigana: "くろう", meaning: "고생"),
        JWordModel(kanji: "偶然", yomigana: "ぐうぜん", meaning: "우연"),
        JWordModel(kanji: "空間", yomigana: "くうかん", meaning: "공간"),
        JWordModel(kanji: "空想", yomigana: "くうそう", meaning: "공상"),
        JWordModel(kanji: "空中", yomigana: "くうちゅう", meaning: "공중"),
        JWordModel(kanji: "区間", yomigana: "くかん", meaning: "구간"),
        JWordModel(kanji: "具体的", yomigana: "ぐたいてき", meaning: "구체적"),
        JWordModel(kanji: "組合", yomigana: "くみあい", meaning: "조합"),
        JWordModel(kanji: "組織", yomigana: "そしき", meaning: "조직"),
        JWordModel(kanji: "繰り返す", yomigana: "くりかえす", meaning: "반복하다"),
        JWordModel(kanji: "暮らし", yomigana: "くらし", meaning: "생활"),
        JWordModel(kanji: "暮れる", yomigana: "くれる", meaning: "저물다"),
        JWordModel(kanji: "苦しい", yomigana: "くるしい", meaning: "괴롭다, 힘들다"),
        JWordModel(kanji: "苦しむ", yomigana: "くるしむ", meaning: "괴로워하다"),
        JWordModel(kanji: "狂う", yomigana: "くるう", meaning: "미치다, 이상해지다"),
        JWordModel(kanji: "加える", yomigana: "くわえる", meaning: "더하다, 가하다"),
        JWordModel(kanji: "詳しい", yomigana: "くわしい", meaning: "자세하다, 상세하다"),
        JWordModel(kanji: "計画", yomigana: "けいかく", meaning: "계획"),
        JWordModel(kanji: "計算", yomigana: "けいさん", meaning: "계산"),
        JWordModel(kanji: "傾向", yomigana: "けいこう", meaning: "경향"),
        JWordModel(kanji: "経験", yomigana: "けいけん", meaning: "경험"),
        JWordModel(kanji: "景気", yomigana: "けいき", meaning: "경기JWordModel(경제 상황)"),
        JWordModel(kanji: "警告", yomigana: "けいこく", meaning: "경고"),
        JWordModel(kanji: "警察", yomigana: "けいさつ", meaning: "경찰"),
        JWordModel(kanji: "芸術", yomigana: "げいじゅつ", meaning: "예술"),
        JWordModel(kanji: "劇場", yomigana: "げきじょう", meaning: "극장"),
        JWordModel(kanji: "決意", yomigana: "けつい", meaning: "결의"),
        JWordModel(kanji: "決定", yomigana: "けってい", meaning: "결정"),
        JWordModel(kanji: "結論", yomigana: "けつろん", meaning: "결론"),
        JWordModel(kanji: "欠点", yomigana: "けってん", meaning: "결점"),
        JWordModel(kanji: "結果", yomigana: "けっか", meaning: "결과"),
        JWordModel(kanji: "結局", yomigana: "けっきょく", meaning: "결국"),
        JWordModel(kanji: "結婚", yomigana: "けっこん", meaning: "결혼"),
        JWordModel(kanji: "欠席", yomigana: "けっせき", meaning: "결석"),
        JWordModel(kanji: "欠如", yomigana: "けつじょ", meaning: "결여"),
        JWordModel(kanji: "健康", yomigana: "けんこう", meaning: "건강"),
        JWordModel(kanji: "見解", yomigana: "けんかい", meaning: "견해"),
        JWordModel(kanji: "研究", yomigana: "けんきゅう", meaning: "연구"),
        JWordModel(kanji: "研究所", yomigana: "けんきゅうじょ", meaning: "연구소"),
        JWordModel(kanji: "見学", yomigana: "けんがく", meaning: "견학"),
        JWordModel(kanji: "権利", yomigana: "けんり", meaning: "권리"),
        JWordModel(kanji: "権力", yomigana: "けんりょく", meaning: "권력"),
        JWordModel(kanji: "現金", yomigana: "げんきん", meaning: "현금"),
        JWordModel(kanji: "現実", yomigana: "げんじつ", meaning: "현실"),
        JWordModel(kanji: "現象", yomigana: "げんしょう", meaning: "현상"),
        JWordModel(kanji: "現代", yomigana: "げんだい", meaning: "현대"),
        JWordModel(kanji: "現場", yomigana: "げんば", meaning: "현장"),
        JWordModel(kanji: "限定", yomigana: "げんてい", meaning: "한정"),
        JWordModel(kanji: "厳重", yomigana: "げんじゅう", meaning: "엄중함"),
        JWordModel(kanji: "厳しい", yomigana: "きびしい", meaning: "엄하다, 심하다"),
        JWordModel(kanji: "現れる", yomigana: "あらわれる", meaning: "나타나다, 드러나다"),
        JWordModel(kanji: "誤解", yomigana: "ごかい", meaning: "오해"),
        JWordModel(kanji: "誤差", yomigana: "ごさ", meaning: "오차"),
        JWordModel(kanji: "誤字", yomigana: "ごじ", meaning: "오자"),
        JWordModel(kanji: "誤り", yomigana: "あやまり", meaning: "실수, 잘못"),
        JWordModel(kanji: "語学", yomigana: "ごがく", meaning: "어학"),
        JWordModel(kanji: "語句", yomigana: "ごく", meaning: "어구, 구절"),
        JWordModel(kanji: "語源", yomigana: "ごげん", meaning: "어원"),
        JWordModel(kanji: "国会", yomigana: "こっかい", meaning: "국회"),
        JWordModel(kanji: "国籍", yomigana: "こくせき", meaning: "국적"),
        JWordModel(kanji: "国民", yomigana: "こくみん", meaning: "국민"),
        JWordModel(kanji: "国立", yomigana: "こくりつ", meaning: "국립"),
        JWordModel(kanji: "穀物", yomigana: "こくもつ", meaning: "곡물"),
        JWordModel(kanji: "克服", yomigana: "こくふく", meaning: "극복"),
        JWordModel(kanji: "個々", yomigana: "ここ", meaning: "개개, 각각"),
        JWordModel(kanji: "個人", yomigana: "こじん", meaning: "개인"),
        JWordModel(kanji: "個性", yomigana: "こせい", meaning: "개성"),
        JWordModel(kanji: "個体", yomigana: "こたい", meaning: "개체"),
        JWordModel(kanji: "故郷", yomigana: "こきょう", meaning: "고향"),
        JWordModel(kanji: "故障", yomigana: "こしょう", meaning: "고장"),
        JWordModel(kanji: "御主人", yomigana: "ごしゅじん", meaning: "남의 남편, 주인"),
        JWordModel(kanji: "腰", yomigana: "こし", meaning: "허리"),
        JWordModel(kanji: "個所", yomigana: "かしょ", meaning: "곳, 부분"),
        JWordModel(kanji: "個数", yomigana: "こすう", meaning: "개수"),
        JWordModel(kanji: "御存じ", yomigana: "ごぞんじ", meaning: "JWordModel(존경) 알고 계심"),
        JWordModel(kanji: "御馳走", yomigana: "ごちそう", meaning: "진수성찬, 대접"),
        JWordModel(kanji: "固定", yomigana: "こてい", meaning: "고정"),
        JWordModel(kanji: "御覧", yomigana: "ごらん", meaning: "JWordModel(존경) 보심"),
        JWordModel(kanji: "好み", yomigana: "このみ", meaning: "기호, 취향"),
        JWordModel(kanji: "好む", yomigana: "このむ", meaning: "좋아하다"),
        JWordModel(kanji: "小包", yomigana: "こづつみ", meaning: "소포"),
        JWordModel(kanji: "小屋", yomigana: "こや", meaning: "오두막, 작은 집"),
        JWordModel(kanji: "雇う", yomigana: "やとう", meaning: "고용하다"),
        JWordModel(kanji: "混雑", yomigana: "こんざつ", meaning: "혼잡"),
        JWordModel(kanji: "混乱", yomigana: "こんらん", meaning: "혼란"),
        JWordModel(kanji: "婚約", yomigana: "こんやく", meaning: "약혼"),
        JWordModel(kanji: "根気", yomigana: "こんき", meaning: "끈기"),
        JWordModel(kanji: "根本", yomigana: "こんぽん", meaning: "근본"),
        JWordModel(kanji: "再会", yomigana: "さいかい", meaning: "재회"),
        JWordModel(kanji: "再建", yomigana: "さいけん", meaning: "재건"),
        JWordModel(kanji: "再生", yomigana: "さいせい", meaning: "재생"),
        JWordModel(kanji: "最終", yomigana: "さいしゅう", meaning: "최종"),
        JWordModel(kanji: "最新", yomigana: "さいしん", meaning: "최신"),
        JWordModel(kanji: "最初", yomigana: "さいしょ", meaning: "처음, 최초"),
        JWordModel(kanji: "最高", yomigana: "さいこう", meaning: "최고"),
        JWordModel(kanji: "最小", yomigana: "さいしょう", meaning: "최소"),
        JWordModel(kanji: "最大", yomigana: "さいだい", meaning: "최대"),
        JWordModel(kanji: "最中", yomigana: "さいちゅう", meaning: "한창 ~중"),
        JWordModel(kanji: "最適", yomigana: "さいてき", meaning: "최적"),
        JWordModel(kanji: "才能", yomigana: "さいのう", meaning: "재능"),
        JWordModel(kanji: "材料", yomigana: "ざいりょう", meaning: "재료"),
        JWordModel(kanji: "財産", yomigana: "ざいさん", meaning: "재산"),
        JWordModel(kanji: "作業", yomigana: "さぎょう", meaning: "작업"),
        JWordModel(kanji: "作品", yomigana: "さくひん", meaning: "작품"),
        JWordModel(kanji: "作法", yomigana: "さほう", meaning: "예의범절, 예법"),
        JWordModel(kanji: "作物", yomigana: "さくもつ", meaning: "작물"),
        JWordModel(kanji: "削除", yomigana: "さくじょ", meaning: "삭제"),
        JWordModel(kanji: "昨年", yomigana: "さくねん", meaning: "작년"),
        JWordModel(kanji: "昨夜", yomigana: "さくや", meaning: "어젯밤"),
        JWordModel(kanji: "叫ぶ", yomigana: "さけぶ", meaning: "외치다, 소리치다"),
        JWordModel(kanji: "避ける", yomigana: "さける", meaning: "피하다"),
        JWordModel(kanji: "支える", yomigana: "ささえる", meaning: "지탱하다, 버티다"),
        JWordModel(kanji: "指す", yomigana: "さす", meaning: "가리키다"),
        JWordModel(kanji: "刺す", yomigana: "さす", meaning: "찌르다, 쏘다"),
        JWordModel(kanji: "注す", yomigana: "さす", meaning: "JWordModel(물 등을) 붓다"),
        JWordModel(kanji: "誘う", yomigana: "さそう", meaning: "권하다, 유도하다"),
        JWordModel(kanji: "撮影", yomigana: "さつえい", meaning: "촬영"),
        JWordModel(kanji: "作家", yomigana: "さっか", meaning: "작가"),
        JWordModel(kanji: "作曲", yomigana: "さっきょく", meaning: "작곡"),
        JWordModel(kanji: "作戦", yomigana: "さくせん", meaning: "작전"),
        JWordModel(kanji: "作成", yomigana: "さくせい", meaning: "작성"),
        JWordModel(kanji: "作製", yomigana: "さくせい", meaning: "제작"),
        JWordModel(kanji: "参加", yomigana: "さんか", meaning: "참가"),
        JWordModel(kanji: "参考", yomigana: "さんこう", meaning: "참고"),
        JWordModel(kanji: "賛成", yomigana: "さんせい", meaning: "찬성"),
        JWordModel(kanji: "産地", yomigana: "さんち", meaning: "산지"),
        JWordModel(kanji: "産業", yomigana: "さんぎょう", meaning: "산업"),
        JWordModel(kanji: "産出", yomigana: "さんしゅつ", meaning: "산출"),
        JWordModel(kanji: "散歩", yomigana: "さんぽ", meaning: "산책"),
        JWordModel(kanji: "残業", yomigana: "ざんぎょう", meaning: "잔업, 야근"),
        JWordModel(kanji: "残念", yomigana: "ざんねん", meaning: "유감"),
        JWordModel(kanji: "仕上げる", yomigana: "しあげる", meaning: "마무리하다"),
        JWordModel(kanji: "仕方", yomigana: "しかた", meaning: "방법, 수단"),
        JWordModel(kanji: "試験", yomigana: "しけん", meaning: "시험"),
        JWordModel(kanji: "支給", yomigana: "しきゅう", meaning: "지급"),
        JWordModel(kanji: "支出", yomigana: "ししゅつ", meaning: "지출"),
        JWordModel(kanji: "指示", yomigana: "しじ", meaning: "지시"),
        JWordModel(kanji: "指摘", yomigana: "してき", meaning: "지적"),
        JWordModel(kanji: "指導", yomigana: "しどう", meaning: "지도"),
        JWordModel(kanji: "自覚", yomigana: "じかく", meaning: "자각"),
        JWordModel(kanji: "資格", yomigana: "しかく", meaning: "자격"),
        JWordModel(kanji: "自給", yomigana: "じきゅう", meaning: "자급"),
        JWordModel(kanji: "自己", yomigana: "じこ", meaning: "자기"),
        JWordModel(kanji: "事故", yomigana: "じこ", meaning: "사고"),
        JWordModel(kanji: "時刻", yomigana: "じこく", meaning: "시각"),
        JWordModel(kanji: "時差", yomigana: "じさ", meaning: "시차"),
        JWordModel(kanji: "自信", yomigana: "じしん", meaning: "자신"),
        JWordModel(kanji: "地震", yomigana: "じしん", meaning: "지진"),
        JWordModel(kanji: "自身", yomigana: "じしん", meaning: "자신JWordModel(스스로)"),
        JWordModel(kanji: "自宅", yomigana: "じたく", meaning: "자택"),
        JWordModel(kanji: "親しい", yomigana: "したしい", meaning: "친하다"),
        JWordModel(kanji: "親しむ", yomigana: "したしむ", meaning: "친하게 지내다"),
        JWordModel(kanji: "従う", yomigana: "したがう", meaning: "따르다"),
        JWordModel(kanji: "従って", yomigana: "したがって", meaning: "따라서"),
        JWordModel(kanji: "支度", yomigana: "したく", meaning: "준비"),
        JWordModel(kanji: "質", yomigana: "しつ", meaning: "질"),
        JWordModel(kanji: "実感", yomigana: "じっかん", meaning: "실감"),
        JWordModel(kanji: "実験", yomigana: "じっけん", meaning: "실험"),
        JWordModel(kanji: "実現", yomigana: "じつげん", meaning: "실현"),
        JWordModel(kanji: "実施", yomigana: "じっし", meaning: "실시"),
        JWordModel(kanji: "実績", yomigana: "じっせき", meaning: "실적"),
        JWordModel(kanji: "実際", yomigana: "じっさい", meaning: "실제"),
        JWordModel(kanji: "実習", yomigana: "じっしゅう", meaning: "실습"),
        JWordModel(kanji: "実用", yomigana: "じつよう", meaning: "실용"),
        JWordModel(kanji: "実力", yomigana: "じつりょく", meaning: "실력"),
        JWordModel(kanji: "実例", yomigana: "じつれい", meaning: "실례"),
        JWordModel(kanji: "失業", yomigana: "しつぎょう", meaning: "실업"),
        JWordModel(kanji: "失恋", yomigana: "しつれん", meaning: "실연"),
        JWordModel(kanji: "失敗", yomigana: "しっぱい", meaning: "실패"),
        JWordModel(kanji: "指定", yomigana: "してい", meaning: "지정"),
        JWordModel(kanji: "指名", yomigana: "しめい", meaning: "지명"),
        JWordModel(kanji: "締切", yomigana: "しめきり", meaning: "마감"),
        JWordModel(kanji: "締め切る", yomigana: "しめきる", meaning: "마감하다"),
        JWordModel(kanji: "締め切り", yomigana: "しめきり", meaning: "마감"),
        JWordModel(kanji: "示す", yomigana: "しめす", meaning: "보이다, 나타내다"),
        JWordModel(kanji: "社交的", yomigana: "しゃこうてき", meaning: "사교적"),
        JWordModel(kanji: "社会", yomigana: "しゃかい", meaning: "사회"),
        JWordModel(kanji: "社会的", yomigana: "しゃかいてき", meaning: "사회적"),
        JWordModel(kanji: "社員", yomigana: "しゃいん", meaning: "사원"),
        JWordModel(kanji: "写生", yomigana: "しゃせい", meaning: "사생JWordModel(그림)"),
        JWordModel(kanji: "写真", yomigana: "しゃしん", meaning: "사진"),
        JWordModel(kanji: "借金", yomigana: "しゃっきん", meaning: "빚, 차금"),
        JWordModel(kanji: "車両", yomigana: "しゃりょう", meaning: "차량"),
        JWordModel(kanji: "種類", yomigana: "しゅるい", meaning: "종류"),
        JWordModel(kanji: "受験", yomigana: "じゅけん", meaning: "수험"),
        JWordModel(kanji: "受信", yomigana: "じゅしん", meaning: "수신"),
        JWordModel(kanji: "受賞", yomigana: "じゅしょう", meaning: "수상"),
        JWordModel(kanji: "受け付け", yomigana: "うけつけ", meaning: "접수"),
        JWordModel(kanji: "受け取る", yomigana: "うけとる", meaning: "받다"),
        JWordModel(kanji: "授与", yomigana: "じゅよ", meaning: "수여"),
        JWordModel(kanji: "需要", yomigana: "じゅよう", meaning: "수요"),
        JWordModel(kanji: "樹木", yomigana: "じゅもく", meaning: "수목"),
        JWordModel(kanji: "順番", yomigana: "じゅんばん", meaning: "순서"),
        JWordModel(kanji: "準備", yomigana: "じゅんび", meaning: "준비"),
        JWordModel(kanji: "順調", yomigana: "じゅんちょう", meaning: "순조로움"),
        JWordModel(kanji: "省略", yomigana: "しょうりゃく", meaning: "생략"),
        JWordModel(kanji: "商業", yomigana: "しょうぎょう", meaning: "상업"),
        JWordModel(kanji: "商社", yomigana: "しょうしゃ", meaning: "상사"),
        JWordModel(kanji: "商品", yomigana: "しょうひん", meaning: "상품"),
        JWordModel(kanji: "消費", yomigana: "しょうひ", meaning: "소비"),
        JWordModel(kanji: "消費者", yomigana: "しょうひしゃ", meaning: "소비자"),
        JWordModel(kanji: "証明", yomigana: "しょうめい", meaning: "증명"),
        JWordModel(kanji: "証明書", yomigana: "しょうめいしょ", meaning: "증명서"),
        JWordModel(kanji: "勝敗", yomigana: "しょうはい", meaning: "승패"),
        JWordModel(kanji: "勝負", yomigana: "しょうぶ", meaning: "승부"),
        JWordModel(kanji: "情報", yomigana: "じょうほう", meaning: "정보"),
        JWordModel(kanji: "状況", yomigana: "じょうきょう", meaning: "상황"),
        JWordModel(kanji: "状態", yomigana: "じょうたい", meaning: "상태"),
        JWordModel(kanji: "常識", yomigana: "じょうしき", meaning: "상식"),
        JWordModel(kanji: "上昇", yomigana: "じょうしょう", meaning: "상승"),
        JWordModel(kanji: "上達", yomigana: "じょうたつ", meaning: "숙달, 향상"),
        JWordModel(kanji: "上等", yomigana: "じょうとう", meaning: "상등, 고급"),
        JWordModel(kanji: "上品", yomigana: "じょうひん", meaning: "고상함, 품위"),
        JWordModel(kanji: "乗客", yomigana: "じょうきゃく", meaning: "승객"),
        JWordModel(kanji: "乗車", yomigana: "じょうしゃ", meaning: "승차"),
        JWordModel(kanji: "職業", yomigana: "しょくぎょう", meaning: "직업"),
        JWordModel(kanji: "職場", yomigana: "しょくば", meaning: "직장"),
        JWordModel(kanji: "食事", yomigana: "しょくじ", meaning: "식사"),
        JWordModel(kanji: "食堂", yomigana: "しょくどう", meaning: "식당"),
        JWordModel(kanji: "食料品", yomigana: "しょくりょうひん", meaning: "식료품"),
        JWordModel(kanji: "植木", yomigana: "うえき", meaning: "화초, 정원수"),
        JWordModel(kanji: "信号", yomigana: "しんごう", meaning: "신호"),
        JWordModel(kanji: "信頼", yomigana: "しんらい", meaning: "신뢰"),
        JWordModel(kanji: "新幹線", yomigana: "しんかんせん", meaning: "신칸센"),
        JWordModel(kanji: "新鮮", yomigana: "しんせん", meaning: "신선함"),
        JWordModel(kanji: "申請", yomigana: "しんせい", meaning: "신청"),
        JWordModel(kanji: "親切", yomigana: "しんせつ", meaning: "친절함"),
        JWordModel(kanji: "親友", yomigana: "しんゆう", meaning: "친구, 절친"),
        JWordModel(kanji: "進学", yomigana: "しんがく", meaning: "진학"),
        JWordModel(kanji: "進歩", yomigana: "しんぽ", meaning: "진보"),
        JWordModel(kanji: "進路", yomigana: "しんろ", meaning: "진로"),
        JWordModel(kanji: "深刻", yomigana: "しんこく", meaning: "심각함"),
        JWordModel(kanji: "深夜", yomigana: "しんや", meaning: "심야"),
        JWordModel(kanji: "信用", yomigana: "しんよう", meaning: "신용"),
        JWordModel(kanji: "信号機", yomigana: "しんごうき", meaning: "신호등"),
        JWordModel(kanji: "人間", yomigana: "にんげん", meaning: "인간"),
        JWordModel(kanji: "人気", yomigana: "にんき", meaning: "인기"),
        JWordModel(kanji: "人数", yomigana: "にんずう", meaning: "인원수"),
        JWordModel(kanji: "入学", yomigana: "にゅうがく", meaning: "입학"),
        JWordModel(kanji: "入場", yomigana: "にゅうじょう", meaning: "입장"),
        JWordModel(kanji: "入院", yomigana: "にゅういん", meaning: "입원"),
        JWordModel(kanji: "入国", yomigana: "にゅうこく", meaning: "입국"),
        JWordModel(kanji: "入金", yomigana: "にゅうきん", meaning: "입금"),
        JWordModel(kanji: "入社", yomigana: "にゅうしゃ", meaning: "입사"),
        JWordModel(kanji: "入手", yomigana: "にゅうしゅ", meaning: "입수"),
        JWordModel(kanji: "入選", yomigana: "にゅうせん", meaning: "입선"),
        JWordModel(kanji: "入力", yomigana: "にゅうりょく", meaning: "입력"),
        JWordModel(kanji: "入門", yomigana: "にゅうもん", meaning: "입문"),
        JWordModel(kanji: "農業", yomigana: "のうぎょう", meaning: "농업"),
        JWordModel(kanji: "農家", yomigana: "のうか", meaning: "농가"),
        JWordModel(kanji: "農民", yomigana: "のうみん", meaning: "농민"),
        JWordModel(kanji: "能力", yomigana: "のうりょく", meaning: "능력"),
        JWordModel(kanji: "発見", yomigana: "はっけん", meaning: "발견"),
        JWordModel(kanji: "発行", yomigana: "はっこう", meaning: "발행"),
        JWordModel(kanji: "発車", yomigana: "はっしゃ", meaning: "출발JWordModel(차량)"),
        JWordModel(kanji: "発展", yomigana: "はってん", meaning: "발전"),
        JWordModel(kanji: "発表", yomigana: "はっぴょう", meaning: "발표"),
        JWordModel(kanji: "発明", yomigana: "はつめい", meaning: "발명"),
        JWordModel(kanji: "発売", yomigana: "はつばい", meaning: "발매"),
        JWordModel(kanji: "発音", yomigana: "はつおん", meaning: "발음"),
        JWordModel(kanji: "反対", yomigana: "はんたい", meaning: "반대"),
        JWordModel(kanji: "反発", yomigana: "はんぱつ", meaning: "반발"),
        JWordModel(kanji: "販売", yomigana: "はんばい", meaning: "판매"),
        JWordModel(kanji: "犯罪", yomigana: "はんざい", meaning: "범죄"),
        JWordModel(kanji: "必死", yomigana: "ひっし", meaning: "필사적"),
        JWordModel(kanji: "必要", yomigana: "ひつよう", meaning: "필요"),
        JWordModel(kanji: "比較", yomigana: "ひかく", meaning: "비교"),
        JWordModel(kanji: "被害", yomigana: "ひがい", meaning: "피해"),
        JWordModel(kanji: "悲劇", yomigana: "ひげき", meaning: "비극"),
        JWordModel(kanji: "非常", yomigana: "ひじょう", meaning: "비상"),
        JWordModel(kanji: "美術", yomigana: "びじゅつ", meaning: "미술"),
        JWordModel(kanji: "美人", yomigana: "びじん", meaning: "미인"),
        JWordModel(kanji: "美容", yomigana: "びよう", meaning: "미용"),
        JWordModel(kanji: "表現", yomigana: "ひょうげん", meaning: "표현"),
        JWordModel(kanji: "表情", yomigana: "ひょうじょう", meaning: "표정"),
        JWordModel(kanji: "表紙", yomigana: "ひょうし", meaning: "표지"),
        JWordModel(kanji: "評価", yomigana: "ひょうか", meaning: "평가"),
        JWordModel(kanji: "病院", yomigana: "びょういん", meaning: "병원"),
        JWordModel(kanji: "病気", yomigana: "びょうき", meaning: "병"),
        JWordModel(kanji: "品物", yomigana: "しなもの", meaning: "물건"),
        JWordModel(kanji: "不安", yomigana: "ふあん", meaning: "불안"),
        JWordModel(kanji: "不便", yomigana: "ふべん", meaning: "불편"),
        JWordModel(kanji: "不足", yomigana: "ふそく", meaning: "부족"),
        JWordModel(kanji: "普通", yomigana: "ふつう", meaning: "보통"),
        JWordModel(kanji: "夫婦", yomigana: "ふうふ", meaning: "부부"),
        JWordModel(kanji: "部分", yomigana: "ぶぶん", meaning: "부분"),
        JWordModel(kanji: "部長", yomigana: "ぶちょう", meaning: "부장"),
        JWordModel(kanji: "文化", yomigana: "ぶんか", meaning: "문화"),
        JWordModel(kanji: "文学", yomigana: "ぶんがく", meaning: "문학"),
        JWordModel(kanji: "文章", yomigana: "ぶんしょう", meaning: "문장"),
        JWordModel(kanji: "分析", yomigana: "ぶんせき", meaning: "분석"),
        JWordModel(kanji: "分野", yomigana: "ぶんや", meaning: "분야"),
        JWordModel(kanji: "平和", yomigana: "へいわ", meaning: "평화"),
        JWordModel(kanji: "平均", yomigana: "へいきん", meaning: "평균"),
        JWordModel(kanji: "返事", yomigana: "へんじ", meaning: "대답, 답장"),
        JWordModel(kanji: "変更", yomigana: "へんこう", meaning: "변경"),
        JWordModel(kanji: "返信", yomigana: "へんしん", meaning: "회신"),
        JWordModel(kanji: "変化", yomigana: "へんか", meaning: "변화"),
        JWordModel(kanji: "便利", yomigana: "べんり", meaning: "편리"),
        JWordModel(kanji: "貿易", yomigana: "ぼうえき", meaning: "무역"),
        JWordModel(kanji: "防止", yomigana: "ぼうし", meaning: "방지"),
        JWordModel(kanji: "方法", yomigana: "ほうほう", meaning: "방법"),
        JWordModel(kanji: "訪問", yomigana: "ほうもん", meaning: "방문"),
        JWordModel(kanji: "報告", yomigana: "ほうこく", meaning: "보고"),
        JWordModel(kanji: "方向", yomigana: "ほうこう", meaning: "방향"),
        JWordModel(kanji: "法律", yomigana: "ほうりつ", meaning: "법률"),
        JWordModel(kanji: "本当", yomigana: "ほんとう", meaning: "정말, 사실"),
        JWordModel(kanji: "翻訳", yomigana: "ほんやく", meaning: "번역"),
        JWordModel(kanji: "毎週", yomigana: "まいしゅう", meaning: "매주"),
        JWordModel(kanji: "毎月", yomigana: "まいつき", meaning: "매달"),
        JWordModel(kanji: "毎年", yomigana: "まいとし", meaning: "매년"),
        JWordModel(kanji: "毎晩", yomigana: "まいばん", meaning: "매일 밤"),
        JWordModel(kanji: "負ける", yomigana: "まける", meaning: "지다"),
        JWordModel(kanji: "真面目", yomigana: "まじめ", meaning: "성실함"),
        JWordModel(kanji: "間違い", yomigana: "まちがい", meaning: "실수"),
        JWordModel(kanji: "間に合う", yomigana: "まにあう", meaning: "시간에 맞다"),
        JWordModel(kanji: "招待", yomigana: "しょうたい", meaning: "초대"),
        JWordModel(kanji: "周囲", yomigana: "しゅうい", meaning: "주위"),
        JWordModel(kanji: "種類", yomigana: "しゅるい", meaning: "종류"),
        JWordModel(kanji: "修理", yomigana: "しゅうり", meaning: "수리"),
        JWordModel(kanji: "集中", yomigana: "しゅうちゅう", meaning: "집중"),
        JWordModel(kanji: "習慣", yomigana: "しゅうかん", meaning: "습관"),
        JWordModel(kanji: "住所", yomigana: "じゅうしょ", meaning: "주소"),
        JWordModel(kanji: "重要", yomigana: "じゅうよう", meaning: "중요"),
        JWordModel(kanji: "授業", yomigana: "じゅぎょう", meaning: "수업"),
        JWordModel(kanji: "受験", yomigana: "じゅけん", meaning: "수험"),
        JWordModel(kanji: "受信", yomigana: "じゅしん", meaning: "수신"),
        JWordModel(kanji: "受賞", yomigana: "じゅしょう", meaning: "수상"),
        JWordModel(kanji: "受け付け", yomigana: "うけつけ", meaning: "접수"),
        JWordModel(kanji: "受け取る", yomigana: "うけとる", meaning: "받다"),
        JWordModel(kanji: "授与", yomigana: "じゅよ", meaning: "수여"),
        JWordModel(kanji: "順番", yomigana: "じゅんばん", meaning: "순서"),
        JWordModel(kanji: "準備", yomigana: "じゅんび", meaning: "준비"),
        JWordModel(kanji: "助ける", yomigana: "たすける", meaning: "돕다"),
        JWordModel(kanji: "詳細", yomigana: "しょうさい", meaning: "상세"),
        JWordModel(kanji: "障害", yomigana: "しょうがい", meaning: "장애"),
        JWordModel(kanji: "条件", yomigana: "じょうけん", meaning: "조건"),
        JWordModel(kanji: "情報", yomigana: "じょうほう", meaning: "정보"),
        JWordModel(kanji: "状況", yomigana: "じょうきょう", meaning: "상황"),
        JWordModel(kanji: "状態", yomigana: "じょうたい", meaning: "상태"),
        JWordModel(kanji: "常識", yomigana: "じょうしき", meaning: "상식"),
        JWordModel(kanji: "上手", yomigana: "じょうず", meaning: "능숙함"),
        JWordModel(kanji: "乗車", yomigana: "じょうしゃ", meaning: "승차"),
        JWordModel(kanji: "乗客", yomigana: "じょうきゃく", meaning: "승객"),
        JWordModel(kanji: "植物", yomigana: "しょくぶつ", meaning: "식물"),
        JWordModel(kanji: "食事", yomigana: "しょくじ", meaning: "식사"),
        JWordModel(kanji: "食堂", yomigana: "しょくどう", meaning: "식당"),
        JWordModel(kanji: "食料品", yomigana: "しょくりょうひん", meaning: "식료품"),
        JWordModel(kanji: "信号", yomigana: "しんごう", meaning: "신호"),
        JWordModel(kanji: "信頼", yomigana: "しんらい", meaning: "신뢰"),
        JWordModel(kanji: "親切", yomigana: "しんせつ", meaning: "친절함"),
        JWordModel(kanji: "親友", yomigana: "しんゆう", meaning: "친구, 절친"),
        JWordModel(kanji: "進学", yomigana: "しんがく", meaning: "진학"),
        JWordModel(kanji: "進歩", yomigana: "しんぽ", meaning: "진보"),
        JWordModel(kanji: "進路", yomigana: "しんろ", meaning: "진로"),
        JWordModel(kanji: "新鮮", yomigana: "しんせん", meaning: "신선함"),
        JWordModel(kanji: "深刻", yomigana: "しんこく", meaning: "심각함"),
        JWordModel(kanji: "深夜", yomigana: "しんや", meaning: "심야"),
        JWordModel(kanji: "信用", yomigana: "しんよう", meaning: "신용"),
        JWordModel(kanji: "信号機", yomigana: "しんごうき", meaning: "신호등"),
        JWordModel(kanji: "人間", yomigana: "にんげん", meaning: "인간"),
        JWordModel(kanji: "人気", yomigana: "にんき", meaning: "인기"),
        JWordModel(kanji: "人数", yomigana: "にんずう", meaning: "인원수"),
        JWordModel(kanji: "入学", yomigana: "にゅうがく", meaning: "입학"),
        JWordModel(kanji: "入場", yomigana: "にゅうじょう", meaning: "입장"),
        JWordModel(kanji: "入院", yomigana: "にゅういん", meaning: "입원"),
        JWordModel(kanji: "入国", yomigana: "にゅうこく", meaning: "입국"),
        JWordModel(kanji: "入金", yomigana: "にゅうきん", meaning: "입금"),
        JWordModel(kanji: "入社", yomigana: "にゅうしゃ", meaning: "입사"),
        JWordModel(kanji: "入手", yomigana: "にゅうしゅ", meaning: "입수"),
        JWordModel(kanji: "入選", yomigana: "にゅうせん", meaning: "입선"),
        JWordModel(kanji: "入力", yomigana: "にゅうりょく", meaning: "입력"),
        JWordModel(kanji: "入門", yomigana: "にゅうもん", meaning: "입문"),
        JWordModel(kanji: "農業", yomigana: "のうぎょう", meaning: "농업"),
        JWordModel(kanji: "農家", yomigana: "のうか", meaning: "농가"),
        JWordModel(kanji: "農民", yomigana: "のうみん", meaning: "농민"),
        JWordModel(kanji: "能力", yomigana: "のうりょく", meaning: "능력"),
        JWordModel(kanji: "発見", yomigana: "はっけん", meaning: "발견"),
        JWordModel(kanji: "発行", yomigana: "はっこう", meaning: "발행"),
        JWordModel(kanji: "発車", yomigana: "はっしゃ", meaning: "출발JWordModel(차량)"),
        JWordModel(kanji: "発展", yomigana: "はってん", meaning: "발전"),
        JWordModel(kanji: "発表", yomigana: "はっぴょう", meaning: "발표"),
        JWordModel(kanji: "発明", yomigana: "はつめい", meaning: "발명"),
        JWordModel(kanji: "発売", yomigana: "はつばい", meaning: "발매"),
        JWordModel(kanji: "発音", yomigana: "はつおん", meaning: "발음"),
        JWordModel(kanji: "反対", yomigana: "はんたい", meaning: "반대"),
        JWordModel(kanji: "反発", yomigana: "はんぱつ", meaning: "반발"),
        JWordModel(kanji: "販売", yomigana: "はんばい", meaning: "판매"),
        JWordModel(kanji: "犯罪", yomigana: "はんざい", meaning: "범죄"),
        JWordModel(kanji: "必死", yomigana: "ひっし", meaning: "필사적"),
        JWordModel(kanji: "必要", yomigana: "ひつよう", meaning: "필요"),
        JWordModel(kanji: "比較", yomigana: "ひかく", meaning: "비교"),
        JWordModel(kanji: "被害", yomigana: "ひがい", meaning: "피해"),
        JWordModel(kanji: "悲劇", yomigana: "ひげき", meaning: "비극"),
        JWordModel(kanji: "非常", yomigana: "ひじょう", meaning: "비상"),
        JWordModel(kanji: "美術", yomigana: "びじゅつ", meaning: "미술"),
        JWordModel(kanji: "美人", yomigana: "びじん", meaning: "미인"),
        JWordModel(kanji: "美容", yomigana: "びよう", meaning: "미용"),
        JWordModel(kanji: "表現", yomigana: "ひょうげん", meaning: "표현"),
        JWordModel(kanji: "表情", yomigana: "ひょうじょう", meaning: "표정"),
        JWordModel(kanji: "表紙", yomigana: "ひょうし", meaning: "표지"),
        JWordModel(kanji: "評価", yomigana: "ひょうか", meaning: "평가"),
        JWordModel(kanji: "病院", yomigana: "びょういん", meaning: "병원"),
        JWordModel(kanji: "病気", yomigana: "びょうき", meaning: "병"),
        JWordModel(kanji: "品物", yomigana: "しなもの", meaning: "물건")
    ]
    for word in JPWordsN2 {
        context.insert(word)
    }
    try? context.save()

        
        
        
    
}

//
//func ModelDataFuncN3 (into context: ModelContext){
//    let JPWordsN3 = [
//        JWordModel(kanji: "飽きる", yomigana: "あきる", meaning: "질리다, 싫증나다"),
//        JWordModel(kanji: "預ける", yomigana: "あずける", meaning: "맡기다"),
//        JWordModel(kanji: "当たる", yomigana: "あたる", meaning: "맞다, 적중하다"),
//        JWordModel(kanji: "余る", yomigana: "あまる", meaning: "남다"),
//        JWordModel(kanji: "編む", yomigana: "あむ", meaning: "짜다"),
//        JWordModel(kanji: "表す", yomigana: "あらわす", meaning: "나타내다, 표현하다"),
//        JWordModel(kanji: "慌てる", yomigana: "あわてる", meaning: "허둥대다"),
//        JWordModel(kanji: "急ぐ", yomigana: "いそぐ", meaning: "서두르다"),
//        JWordModel(kanji: "挑む", yomigana: "いどむ", meaning: "도전하다"),
//        JWordModel(kanji: "植える", yomigana: "うえる", meaning: "심다"),
//        JWordModel(kanji: "受け取る", yomigana: "うけとる", meaning: "수취하다, 받다"),
//        JWordModel(kanji: "疑う", yomigana: "うたがう", meaning: "의심하다"),
//        JWordModel(kanji: "打つ", yomigana: "うつ", meaning: "치다"),
//        JWordModel(kanji: "移る", yomigana: "うつる", meaning: "옮기다, 이동하다"),
//        JWordModel(kanji: "写す", yomigana: "うつす", meaning: "베끼다, 복사하다"),
//        JWordModel(kanji: "映す", yomigana: "うつす", meaning: "비추다"),
//        JWordModel(kanji: "奪う", yomigana: "うばう", meaning: "빼앗다"),
//        JWordModel(kanji: "埋める", yomigana: "うめる", meaning: "묻다, 메우다"),
//        JWordModel(kanji: "売れる", yomigana: "うれる", meaning: "팔리다"),
//        JWordModel(kanji: "得る", yomigana: "える", meaning: "얻다"),
//        JWordModel(kanji: "追いかける", yomigana: "おいかける", meaning: "뒤쫓다"),
//        JWordModel(kanji: "覆う", yomigana: "おおう", meaning: "덮다, 씌우다"),
//        JWordModel(kanji: "起こる", yomigana: "おこる", meaning: "일어나다, 발생하다"),
//        JWordModel(kanji: "驚く", yomigana: "おどろく", meaning: "놀라다"),
//        JWordModel(kanji: "思い出す", yomigana: "おもいだす", meaning: "생각해내다"),
//        JWordModel(kanji: "泳ぐ", yomigana: "およぐ", meaning: "헤엄치다"),
//        JWordModel(kanji: "下ろす", yomigana: "おろす", meaning: "내리다, 내놓다"),
//        JWordModel(kanji: "終える", yomigana: "おえる", meaning: "끝내다"),
//        JWordModel(kanji: "変える", yomigana: "かえる", meaning: "바꾸다"),
//        JWordModel(kanji: "抱える", yomigana: "かかえる", meaning: "안다, 끌어안다"),
//        JWordModel(kanji: "掛ける", yomigana: "かける", meaning: "걸다, JWordModel(시간/돈) 걸리다"),
//        JWordModel(kanji: "飾る", yomigana: "かざる", meaning: "장식하다"),
//        JWordModel(kanji: "数える", yomigana: "かぞえる", meaning: "세다, 계산하다"),
//        JWordModel(kanji: "語る", yomigana: "かたる", meaning: "말하다, 이야기하다"),
//        JWordModel(kanji: "勝つ", yomigana: "かつ", meaning: "이기다"),
//        JWordModel(kanji: "被る", yomigana: "かぶる", meaning: "쓰다, 뒤집어쓰다"),
//        JWordModel(kanji: "通う", yomigana: "かよう", meaning: "다니다"),
//        JWordModel(kanji: "代える", yomigana: "かえる", meaning: "대신하다, 바꾸다"),
//        JWordModel(kanji: "変わる", yomigana: "かわる", meaning: "변하다"),
//        JWordModel(kanji: "乾く", yomigana: "かわく", meaning: "마르다"),
//        JWordModel(kanji: "考える", yomigana: "かんがえる", meaning: "생각하다"),
//        JWordModel(kanji: "聞こえる", yomigana: "きこえる", meaning: "들리다"),
//        JWordModel(kanji: "決まる", yomigana: "きまる", meaning: "정해지다"),
//        JWordModel(kanji: "決める", yomigana: "きめる", meaning: "정하다"),
//        JWordModel(kanji: "切れる", yomigana: "きれる", meaning: "끊어지다, 잘리다"),
//        JWordModel(kanji: "気付く", yomigana: "きづく", meaning: "깨닫다, 눈치채다"),
//        JWordModel(kanji: "暮らす", yomigana: "くらす", meaning: "살다, 생활하다"),
//        JWordModel(kanji: "比べる", yomigana: "くらべる", meaning: "비교하다"),
//        JWordModel(kanji: "繰り返す", yomigana: "くりかえす", meaning: "반복하다"),
//        JWordModel(kanji: "加える", yomigana: "くわえる", meaning: "더하다, 가하다"),
//        JWordModel(kanji: "答える", yomigana: "こたえる", meaning: "대답하다"),
//        JWordModel(kanji: "断る", yomigana: "ことわる", meaning: "거절하다"),
//        JWordModel(kanji: "込む", yomigana: "こむ", meaning: "붐비다, 혼잡하다"),
//        JWordModel(kanji: "壊す", yomigana: "こわす", meaning: "부수다, 망가뜨리다"),
//        JWordModel(kanji: "壊れる", yomigana: "こわれる", meaning: "부서지다, 망가지다"),
//        JWordModel(kanji: "探す", yomigana: "さがす", meaning: "찾다"),
//        JWordModel(kanji: "避ける", yomigana: "さける", meaning: "피하다"),
//        JWordModel(kanji: "誘う", yomigana: "さそう", meaning: "권하다, 유도하다"),
//        JWordModel(kanji: "触る", yomigana: "さわる", meaning: "만지다, 닿다"),
//        JWordModel(kanji: "叱る", yomigana: "しかる", meaning: "꾸짖다"),
//        JWordModel(kanji: "閉まる", yomigana: "しまる", meaning: "닫히다"),
//        JWordModel(kanji: "閉める", yomigana: "しめる", meaning: "닫다"),
//        JWordModel(kanji: "締める", yomigana: "しめる", meaning: "매다, 조이다"),
//        JWordModel(kanji: "知らせる", yomigana: "しらせる", meaning: "알리다"),
//        JWordModel(kanji: "調べる", yomigana: "しらべる", meaning: "조사하다"),
//        JWordModel(kanji: "信じる", yomigana: "しんじる", meaning: "믿다"),
//        JWordModel(kanji: "進む", yomigana: "すすむ", meaning: "나아가다"),
//        JWordModel(kanji: "進める", yomigana: "すすめる", meaning: "나아가게 하다, 진행시키다"),
//        JWordModel(kanji: "過ぎる", yomigana: "すぎる", meaning: "지나가다"),
//        JWordModel(kanji: "捨てる", yomigana: "すてる", meaning: "버리다"),
//        JWordModel(kanji: "育てる", yomigana: "そだてる", meaning: "키우다"),
//        JWordModel(kanji: "倒れる", yomigana: "たおれる", meaning: "쓰러지다"),
//        JWordModel(kanji: "確かめる", yomigana: "たしかめる", meaning: "확인하다"),
//        JWordModel(kanji: "戦う", yomigana: "たたかう", meaning: "싸우다"),
//        JWordModel(kanji: "畳む", yomigana: "たたむ", meaning: "개다, 접다"),
//        JWordModel(kanji: "経つ", yomigana: "たつ", meaning: "지나다, 경과하다"),
//        JWordModel(kanji: "黙る", yomigana: "だまる", meaning: "입 다물다"),
//        JWordModel(kanji: "頼る", yomigana: "たよる", meaning: "의지하다"),
//        JWordModel(kanji: "違う", yomigana: "ちがう", meaning: "다르다"),
//        JWordModel(kanji: "疲れる", yomigana: "つかれる", meaning: "피곤하다"),
//        JWordModel(kanji: "伝わる", yomigana: "つたわる", meaning: "전해지다"),
//        JWordModel(kanji: "捕まえる", yomigana: "つかまえる", meaning: "잡다"),
//        JWordModel(kanji: "続く", yomigana: "つづく", meaning: "계속되다"),
//        JWordModel(kanji: "続ける", yomigana: "つづける", meaning: "계속하다"),
//        JWordModel(kanji: "包む", yomigana: "つつむ", meaning: "싸다, 포장하다"),
//        JWordModel(kanji: "勤める", yomigana: "つとめる", meaning: "근무하다"),
//        JWordModel(kanji: "連れる", yomigana: "つれる", meaning: "데려가다, 동반하다"),
//        JWordModel(kanji: "手伝う", yomigana: "てつだう", meaning: "돕다"),
//        JWordModel(kanji: "届ける", yomigana: "とどける", meaning: "전달하다"),
//        JWordModel(kanji: "泊まる", yomigana: "とまる", meaning: "묵다, 숙박하다"),
//        JWordModel(kanji: "止める", yomigana: "とめる", meaning: "멈추다"),
//        JWordModel(kanji: "直す", yomigana: "なおす", meaning: "고치다"),
//        JWordModel(kanji: "治る", yomigana: "なおる", meaning: "치료되다, 낫다"),
//        JWordModel(kanji: "流れる", yomigana: "ながれる", meaning: "흐르다"),
//        JWordModel(kanji: "投げる", yomigana: "なげる", meaning: "던지다"),
//        JWordModel(kanji: "慣れる", yomigana: "なれる", meaning: "익숙해지다"),
//        JWordModel(kanji: "逃げる", yomigana: "にげる", meaning: "도망가다"),
//        JWordModel(kanji: "抜く", yomigana: "ぬく", meaning: "뽑다"),
//        JWordModel(kanji: "塗る", yomigana: "ぬる", meaning: "바르다, 칠하다"),
//        JWordModel(kanji: "願う", yomigana: "ねがう", meaning: "바라다, 기원하다"),
//        JWordModel(kanji: "残る", yomigana: "のこる", meaning: "남다"),
//        JWordModel(kanji: "乗せる", yomigana: "のせる", meaning: "태우다, 싣다"),
//        JWordModel(kanji: "乗る", yomigana: "のる", meaning: "타다"),
//        JWordModel(kanji: "運ぶ", yomigana: "はこぶ", meaning: "운반하다"),
//        JWordModel(kanji: "始まる", yomigana: "はじまる", meaning: "시작되다"),
//        JWordModel(kanji: "始める", yomigana: "はじめる", meaning: "시작하다"),
//        JWordModel(kanji: "外す", yomigana: "はずす", meaning: "떼다, 벗기다"),
//        JWordModel(kanji: "働く", yomigana: "はたらく", meaning: "일하다"),
//        JWordModel(kanji: "払う", yomigana: "はらう", meaning: "지불하다"),
//        JWordModel(kanji: "引く", yomigana: "ひく", meaning: "끌다, 당기다"),
//        JWordModel(kanji: "弾く", yomigana: "ひく", meaning: "JWordModel(악기)연주하다"),
//        JWordModel(kanji: "開く", yomigana: "ひらく", meaning: "열다"),
//        JWordModel(kanji: "増やす", yomigana: "ふやす", meaning: "늘리다"),
//        JWordModel(kanji: "増える", yomigana: "ふえる", meaning: "늘다"),
//        JWordModel(kanji: "降る", yomigana: "ふる", meaning: "내리다JWordModel(비, 눈 등)"),
//        JWordModel(kanji: "踏む", yomigana: "ふむ", meaning: "밟다"),
//        JWordModel(kanji: "曲がる", yomigana: "まがる", meaning: "구부러지다, 돌다"),
//        JWordModel(kanji: "負ける", yomigana: "まける", meaning: "지다"),
//        JWordModel(kanji: "守る", yomigana: "まもる", meaning: "지키다"),
//        JWordModel(kanji: "回す", yomigana: "まわす", meaning: "돌리다"),
//        JWordModel(kanji: "見える", yomigana: "みえる", meaning: "보이다"),
//        JWordModel(kanji: "見つかる", yomigana: "みつかる", meaning: "발견되다"),
//        JWordModel(kanji: "見つける", yomigana: "みつける", meaning: "찾아내다"),
//        JWordModel(kanji: "認める", yomigana: "みとめる", meaning: "인정하다"),
//        JWordModel(kanji: "向かう", yomigana: "むかう", meaning: "향하다"),
//        JWordModel(kanji: "迎える", yomigana: "むかえる", meaning: "맞이하다"),
//        JWordModel(kanji: "結ぶ", yomigana: "むすぶ", meaning: "묶다, 잇다"),
//        JWordModel(kanji: "群れる", yomigana: "むれる", meaning: "무리를 이루다"),
//        JWordModel(kanji: "申し込む", yomigana: "もうしこむ", meaning: "신청하다"),
//        JWordModel(kanji: "燃える", yomigana: "もえる", meaning: "타다, 불타다"),
//        JWordModel(kanji: "盛る", yomigana: "もる", meaning: "담다, 성하다"),
//        JWordModel(kanji: "焼ける", yomigana: "やける", meaning: "타다, 구워지다"),
//        JWordModel(kanji: "止む", yomigana: "やむ", meaning: "멈추다"),
//        JWordModel(kanji: "辞める", yomigana: "やめる", meaning: "그만두다"),
//        JWordModel(kanji: "破る", yomigana: "やぶる", meaning: "찢다, 깨뜨리다"),
//        JWordModel(kanji: "やる", yomigana: "やる", meaning: "하다, 주다"),
//        JWordModel(kanji: "許す", yomigana: "ゆるす", meaning: "허락하다"),
//        JWordModel(kanji: "寄る", yomigana: "よる", meaning: "들르다, 가까이 가다"),
//        JWordModel(kanji: "呼ぶ", yomigana: "よぶ", meaning: "부르다"),
//        JWordModel(kanji: "喜ぶ", yomigana: "よろこぶ", meaning: "기뻐하다"),
//        JWordModel(kanji: "分かる", yomigana: "わかる", meaning: "알다, 이해하다"),
//        JWordModel(kanji: "渡す", yomigana: "わたす", meaning: "건네주다"),
//        JWordModel(kanji: "渡る", yomigana: "わたる", meaning: "건너다"),
//        JWordModel(kanji: "笑う", yomigana: "わらう", meaning: "웃다"),
//        JWordModel(kanji: "悪化", yomigana: "あっか", meaning: "악화"),
//        JWordModel(kanji: "安心", yomigana: "あんしん", meaning: "안심"),
//        JWordModel(kanji: "案内", yomigana: "あんない", meaning: "안내"),
//        JWordModel(kanji: "以外", yomigana: "いがい", meaning: "이외"),
//        JWordModel(kanji: "医学", yomigana: "いがく", meaning: "의학"),
//        JWordModel(kanji: "生きる", yomigana: "いきる", meaning: "살다"),
//        JWordModel(kanji: "意見", yomigana: "いけん", meaning: "의견"),
//        JWordModel(kanji: "一度", yomigana: "いちど", meaning: "한 번"),
//        JWordModel(kanji: "一部", yomigana: "いちぶ", meaning: "일부"),
//        JWordModel(kanji: "一般", yomigana: "いっぱん", meaning: "일반"),
//        JWordModel(kanji: "一方", yomigana: "いっぽう", meaning: "한편, 한쪽"),
//        JWordModel(kanji: "一生", yomigana: "いっしょう", meaning: "일생, 평생"),
//        JWordModel(kanji: "一種", yomigana: "いっしゅ", meaning: "일종"),
//        JWordModel(kanji: "一瞬", yomigana: "いっしゅん", meaning: "순간"),
//        JWordModel(kanji: "一致", yomigana: "いっち", meaning: "일치"),
//        JWordModel(kanji: "一家", yomigana: "いっか", meaning: "한 집안"),
//        JWordModel(kanji: "以内", yomigana: "いない", meaning: "~이내"),
//        JWordModel(kanji: "田舎", yomigana: "いなか", meaning: "시골"),
//        JWordModel(kanji: "祈る", yomigana: "いのる", meaning: "기도하다"),
//        JWordModel(kanji: "今後", yomigana: "こんご", meaning: "이후, 앞으로"),
//        JWordModel(kanji: "意味", yomigana: "いみ", meaning: "의미"),
//        JWordModel(kanji: "以来", yomigana: "いらい", meaning: "이래, 이후"),
//        JWordModel(kanji: "入れる", yomigana: "いれる", meaning: "넣다"),
//        JWordModel(kanji: "色", yomigana: "いろ", meaning: "색"),
//        JWordModel(kanji: "岩", yomigana: "いわ", meaning: "바위"),
//        JWordModel(kanji: "祝い", yomigana: "いわい", meaning: "축하"),
//        JWordModel(kanji: "祝う", yomigana: "いわう", meaning: "축하하다"),
//        JWordModel(kanji: "引用", yomigana: "いんよう", meaning: "인용"),
//        JWordModel(kanji: "上", yomigana: "うえ", meaning: "위"),
//        JWordModel(kanji: "受ける", yomigana: "うける", meaning: "받다"),
//        JWordModel(kanji: "動かす", yomigana: "うごかす", meaning: "움직이다JWordModel(타)"),
//        JWordModel(kanji: "動く", yomigana: "うごく", meaning: "움직이다JWordModel(자)"),
//        JWordModel(kanji: "失う", yomigana: "うしなう", meaning: "잃다"),
//        JWordModel(kanji: "嘘", yomigana: "うそ", meaning: "거짓말"),
//        JWordModel(kanji: "疑う", yomigana: "うたがう", meaning: "의심하다"),
//        JWordModel(kanji: "歌う", yomigana: "うたう", meaning: "노래하다"),
//        JWordModel(kanji: "内", yomigana: "うち", meaning: "안, 내부"),
//        JWordModel(kanji: "移す", yomigana: "うつす", meaning: "옮기다"),
//        JWordModel(kanji: "写す", yomigana: "うつす", meaning: "베끼다"),
//        JWordModel(kanji: "移る", yomigana: "うつる", meaning: "옮겨지다"),
//        JWordModel(kanji: "写る", yomigana: "うつる", meaning: "찍히다"),
//        JWordModel(kanji: "訴える", yomigana: "うったえる", meaning: "호소하다"),
//        JWordModel(kanji: "腕", yomigana: "うで", meaning: "팔"),
//        JWordModel(kanji: "生まれる", yomigana: "うまれる", meaning: "태어나다"),
//        JWordModel(kanji: "生む", yomigana: "うむ", meaning: "낳다"),
//        JWordModel(kanji: "梅雨", yomigana: "つゆ", meaning: "장마"),
//        JWordModel(kanji: "裏", yomigana: "うら", meaning: "뒤, 뒷면"),
//        JWordModel(kanji: "売り場", yomigana: "うりば", meaning: "매장"),
//        JWordModel(kanji: "売る", yomigana: "うる", meaning: "팔다"),
//        JWordModel(kanji: "嬉しい", yomigana: "うれしい", meaning: "기쁘다"),
//        JWordModel(kanji: "運転", yomigana: "うんてん", meaning: "운전"),
//        JWordModel(kanji: "運動", yomigana: "うんどう", meaning: "운동"),
//        JWordModel(kanji: "映画", yomigana: "えいが", meaning: "영화"),
//        JWordModel(kanji: "映画館", yomigana: "えいがかん", meaning: "영화관"),
//        JWordModel(kanji: "営業", yomigana: "えいぎょう", meaning: "영업"),
//        JWordModel(kanji: "永遠", yomigana: "えいえん", meaning: "영원"),
//        JWordModel(kanji: "英語", yomigana: "えいご", meaning: "영어"),
//        JWordModel(kanji: "衛生", yomigana: "えいせい", meaning: "위생"),
//        JWordModel(kanji: "駅", yomigana: "えき", meaning: "역"),
//        JWordModel(kanji: "エネルギー", yomigana: "エネルギー", meaning: "에너지"),
//        JWordModel(kanji: "選ぶ", yomigana: "えらぶ", meaning: "고르다"),
//        JWordModel(kanji: "遠い", yomigana: "とおい", meaning: "멀다"),
//        JWordModel(kanji: "遠慮", yomigana: "えんりょ", meaning: "사양"),
//        JWordModel(kanji: "塩", yomigana: "しお", meaning: "소금"),
//        JWordModel(kanji: "円", yomigana: "えん", meaning: "엔"),
//        JWordModel(kanji: "演技", yomigana: "えんぎ", meaning: "연기"),
//        JWordModel(kanji: "演説", yomigana: "えんぜつ", meaning: "연설"),
//        JWordModel(kanji: "演奏", yomigana: "えんそう", meaning: "연주"),
//        JWordModel(kanji: "演出", yomigana: "えんしゅつ", meaning: "연출"),
//        JWordModel(kanji: "遠足", yomigana: "えんそく", meaning: "소풍"),
//        JWordModel(kanji: "延長", yomigana: "えんちょう", meaning: "연장"),
//        JWordModel(kanji: "老い", yomigana: "おい", meaning: "늙음"),
//        JWordModel(kanji: "追い越す", yomigana: "おいこす", meaning: "추월하다"),
//        JWordModel(kanji: "応援", yomigana: "おうえん", meaning: "응원"),
//        JWordModel(kanji: "王", yomigana: "おう", meaning: "왕"),
//        JWordModel(kanji: "王様", yomigana: "おうさま", meaning: "임금님"),
//        JWordModel(kanji: "多い", yomigana: "おおい", meaning: "많다"),
//        JWordModel(kanji: "大きい", yomigana: "おおきい", meaning: "크다"),
//        JWordModel(kanji: "大きな", yomigana: "おおきな", meaning: "큰"),
//        JWordModel(kanji: "大勢", yomigana: "おおぜい", meaning: "많은 사람"),
//        JWordModel(kanji: "お菓子", yomigana: "おかし", meaning: "과자"),
//        JWordModel(kanji: "お金", yomigana: "おかね", meaning: "돈"),
//        JWordModel(kanji: "起きる", yomigana: "おきる", meaning: "일어나다"),
//        JWordModel(kanji: "置く", yomigana: "おく", meaning: "두다"),
//        JWordModel(kanji: "贈る", yomigana: "おくる", meaning: "보내다"),
//        JWordModel(kanji: "遅れる", yomigana: "おくれる", meaning: "늦다"),
//        JWordModel(kanji: "起こす", yomigana: "おこす", meaning: "일으키다"),
//        JWordModel(kanji: "怒る", yomigana: "おこる", meaning: "화내다"),
//        JWordModel(kanji: "行う", yomigana: "おこなう", meaning: "행하다"),
//        JWordModel(kanji: "教える", yomigana: "おしえる", meaning: "가르치다"),
//        JWordModel(kanji: "押す", yomigana: "おす", meaning: "누르다"),
//        JWordModel(kanji: "遅い", yomigana: "おそい", meaning: "느리다"),
//        JWordModel(kanji: "恐ろしい", yomigana: "おそろしい", meaning: "무섭다"),
//        JWordModel(kanji: "落ちる", yomigana: "おちる", meaning: "떨어지다"),
//        JWordModel(kanji: "落とす", yomigana: "おとす", meaning: "떨어뜨리다"),
//        JWordModel(kanji: "音", yomigana: "おと", meaning: "소리"),
//        JWordModel(kanji: "踊る", yomigana: "おどる", meaning: "춤추다"),
//        JWordModel(kanji: "驚く", yomigana: "おどろく", meaning: "놀라다"),
//        JWordModel(kanji: "お腹", yomigana: "おなか", meaning: "배"),
//        JWordModel(kanji: "同じ", yomigana: "おなじ", meaning: "같다"),
//        JWordModel(kanji: "お願い", yomigana: "おねがい", meaning: "부탁"),
//        JWordModel(kanji: "おば", yomigana: "おば", meaning: "이모, 고모"),
//        JWordModel(kanji: "おばさん", yomigana: "おばさん", meaning: "아주머니"),
//        JWordModel(kanji: "覚える", yomigana: "おぼえる", meaning: "기억하다"),
//        JWordModel(kanji: "思い出", yomigana: "おもいで", meaning: "추억"),
//        JWordModel(kanji: "思い出す", yomigana: "おもいだす", meaning: "생각해내다"),
//        JWordModel(kanji: "思う", yomigana: "おもう", meaning: "생각하다"),
//        JWordModel(kanji: "泳ぐ", yomigana: "およぐ", meaning: "헤엄치다"),
//        JWordModel(kanji: "降りる", yomigana: "おりる", meaning: "내리다"),
//        JWordModel(kanji: "下ろす", yomigana: "おろす", meaning: "내리다, 내놓다"),
//        JWordModel(kanji: "終わる", yomigana: "おわる", meaning: "끝나다"),
//        JWordModel(kanji: "音楽", yomigana: "おんがく", meaning: "음악"),
//        JWordModel(kanji: "女", yomigana: "おんな", meaning: "여자"),
//        JWordModel(kanji: "女の子", yomigana: "おんなのこ", meaning: "여자아이"),
//        JWordModel(kanji: "会", yomigana: "かい", meaning: "모임, 회"),
//        JWordModel(kanji: "会員", yomigana: "かいいん", meaning: "회원"),
//        JWordModel(kanji: "海外", yomigana: "かいがい", meaning: "해외"),
//        JWordModel(kanji: "会議", yomigana: "かいぎ", meaning: "회의"),
//        JWordModel(kanji: "会場", yomigana: "かいじょう", meaning: "회장"),
//        JWordModel(kanji: "回数", yomigana: "かいすう", meaning: "횟수"),
//        JWordModel(kanji: "回転", yomigana: "かいてん", meaning: "회전"),
//        JWordModel(kanji: "解決", yomigana: "かいけつ", meaning: "해결"),
//        JWordModel(kanji: "会話", yomigana: "かいわ", meaning: "회화"),
//        JWordModel(kanji: "顔", yomigana: "かお", meaning: "얼굴"),
//        JWordModel(kanji: "科学", yomigana: "かがく", meaning: "과학"),
//        JWordModel(kanji: "鏡", yomigana: "かがみ", meaning: "거울"),
//        JWordModel(kanji: "掛ける", yomigana: "かける", meaning: "걸다"),
//        JWordModel(kanji: "火事", yomigana: "かじ", meaning: "화재"),
//        JWordModel(kanji: "家事", yomigana: "かじ", meaning: "집안일"),
//        JWordModel(kanji: "貸す", yomigana: "かす", meaning: "빌려주다"),
//        JWordModel(kanji: "数", yomigana: "かず", meaning: "수, 숫자"),
//        JWordModel(kanji: "風", yomigana: "かぜ", meaning: "바람"),
//        JWordModel(kanji: "風邪", yomigana: "かぜ", meaning: "감기"),
//        JWordModel(kanji: "家族", yomigana: "かぞく", meaning: "가족"),
//        JWordModel(kanji: "方", yomigana: "かた", meaning: "방법, 분"),
//        JWordModel(kanji: "形", yomigana: "かたち", meaning: "모양"),
//        JWordModel(kanji: "勝つ", yomigana: "かつ", meaning: "이기다"),
//        JWordModel(kanji: "家庭", yomigana: "かてい", meaning: "가정"),
//        JWordModel(kanji: "家庭教師", yomigana: "かていきょうし", meaning: "가정교사"),
//        JWordModel(kanji: "学科", yomigana: "がっか", meaning: "학과"),
//        JWordModel(kanji: "学会", yomigana: "がっかい", meaning: "학회"),
//        JWordModel(kanji: "学期", yomigana: "がっき", meaning: "학기"),
//        JWordModel(kanji: "学生", yomigana: "がくせい", meaning: "학생"),
//        JWordModel(kanji: "学者", yomigana: "がくしゃ", meaning: "학자"),
//        JWordModel(kanji: "学習", yomigana: "がくしゅう", meaning: "학습"),
//        JWordModel(kanji: "学問", yomigana: "がくもん", meaning: "학문"),
//        JWordModel(kanji: "楽器", yomigana: "がっき", meaning: "악기"),
//        JWordModel(kanji: "活動", yomigana: "かつどう", meaning: "활동"),
//        JWordModel(kanji: "活発", yomigana: "かっぱつ", meaning: "활발함"),
//        JWordModel(kanji: "活用", yomigana: "かつよう", meaning: "활용"),
//        JWordModel(kanji: "家内", yomigana: "かない", meaning: "아내, 집안"),
//        JWordModel(kanji: "必ず", yomigana: "かならず", meaning: "반드시"),
//        JWordModel(kanji: "彼", yomigana: "かれ", meaning: "그, 그 사람"),
//        JWordModel(kanji: "彼女", yomigana: "かのじょ", meaning: "그녀"),
//        JWordModel(kanji: "可能", yomigana: "かのう", meaning: "가능"),
//        JWordModel(kanji: "可能性", yomigana: "かのうせい", meaning: "가능성"),
//        JWordModel(kanji: "壁", yomigana: "かべ", meaning: "벽"),
//        JWordModel(kanji: "株", yomigana: "かぶ", meaning: "주식, 그루JWordModel(식물)"),
//        JWordModel(kanji: "被る", yomigana: "かぶる", meaning: "JWordModel(모자 등을) 쓰다"),
//        JWordModel(kanji: "紙", yomigana: "かみ", meaning: "종이"),
//        JWordModel(kanji: "髪", yomigana: "かみ", meaning: "머리카락"),
//        JWordModel(kanji: "神", yomigana: "かみ", meaning: "신"),
//        JWordModel(kanji: "川", yomigana: "かわ", meaning: "강"),
//        JWordModel(kanji: "皮", yomigana: "かわ", meaning: "껍질"),
//        JWordModel(kanji: "変える", yomigana: "かえる", meaning: "바꾸다"),
//        JWordModel(kanji: "替える", yomigana: "かえる", meaning: "교체하다"),
//        JWordModel(kanji: "帰る", yomigana: "かえる", meaning: "돌아가다"),
//        JWordModel(kanji: "買う", yomigana: "かう", meaning: "사다"),
//        JWordModel(kanji: "飼う", yomigana: "かう", meaning: "JWordModel(동물을) 기르다"),
//        JWordModel(kanji: "価格", yomigana: "かかく", meaning: "가격"),
//        JWordModel(kanji: "科目", yomigana: "かもく", meaning: "과목"),
//        JWordModel(kanji: "通う", yomigana: "かよう", meaning: "다니다"),
//        JWordModel(kanji: "彼ら", yomigana: "かれら", meaning: "그들"),
//        JWordModel(kanji: "乾く", yomigana: "かわく", meaning: "마르다"),
//        JWordModel(kanji: "代わり", yomigana: "かわり", meaning: "대신, 대리"),
//        JWordModel(kanji: "代わる", yomigana: "かわる", meaning: "대신하다"),
//        JWordModel(kanji: "変わる", yomigana: "かわる", meaning: "변하다"),
//        JWordModel(kanji: "間", yomigana: "あいだ", meaning: "사이, 간격"),
//        JWordModel(kanji: "間違い", yomigana: "まちがい", meaning: "실수, 잘못"),
//        JWordModel(kanji: "間違える", yomigana: "まちがえる", meaning: "실수하다"),
//        JWordModel(kanji: "感じ", yomigana: "かんじ", meaning: "느낌"),
//        JWordModel(kanji: "感じる", yomigana: "かんじる", meaning: "느끼다"),
//        JWordModel(kanji: "感動", yomigana: "かんどう", meaning: "감동"),
//        JWordModel(kanji: "感謝", yomigana: "かんしゃ", meaning: "감사"),
//        JWordModel(kanji: "簡単", yomigana: "かんたん", meaning: "간단함"),
//        JWordModel(kanji: "看護師", yomigana: "かんごし", meaning: "간호사"),
//        JWordModel(kanji: "観光", yomigana: "かんこう", meaning: "관광"),
//        JWordModel(kanji: "観察", yomigana: "かんさつ", meaning: "관찰"),
//        JWordModel(kanji: "完成", yomigana: "かんせい", meaning: "완성"),
//        JWordModel(kanji: "完全", yomigana: "かんぜん", meaning: "완전함"),
//        JWordModel(kanji: "関係", yomigana: "かんけい", meaning: "관계"),
//        JWordModel(kanji: "関心", yomigana: "かんしん", meaning: "관심"),
//        JWordModel(kanji: "感心", yomigana: "かんしん", meaning: "감탄, 감명"),
//        JWordModel(kanji: "感想", yomigana: "かんそう", meaning: "감상, 소감"),
//        JWordModel(kanji: "感情", yomigana: "かんじょう", meaning: "감정"),
//        JWordModel(kanji: "感覚", yomigana: "かんかく", meaning: "감각"),
//        JWordModel(kanji: "関する", yomigana: "かんする", meaning: "~에 관한"),
//        JWordModel(kanji: "看板", yomigana: "かんばん", meaning: "간판"),
//        JWordModel(kanji: "管理", yomigana: "かんり", meaning: "관리"),
//        JWordModel(kanji: "完了", yomigana: "かんりょう", meaning: "완료"),
//        JWordModel(kanji: "期間", yomigana: "きかん", meaning: "기간"),
//        JWordModel(kanji: "機会", yomigana: "きかい", meaning: "기회"),
//        JWordModel(kanji: "機械", yomigana: "きかい", meaning: "기계"),
//        JWordModel(kanji: "危険", yomigana: "きけん", meaning: "위험"),
//        JWordModel(kanji: "記事", yomigana: "きじ", meaning: "기사JWordModel(신문 등)"),
//        JWordModel(kanji: "季節", yomigana: "きせつ", meaning: "계절"),
//        JWordModel(kanji: "規則", yomigana: "きそく", meaning: "규칙"),
//        JWordModel(kanji: "基本", yomigana: "きほん", meaning: "기본"),
//        JWordModel(kanji: "希望", yomigana: "きぼう", meaning: "희망"),
//        JWordModel(kanji: "決して", yomigana: "けっして", meaning: "결코"),
//        JWordModel(kanji: "結局", yomigana: "けっきょく", meaning: "결국"),
//        JWordModel(kanji: "結婚", yomigana: "けっこん", meaning: "결혼"),
//        JWordModel(kanji: "結果", yomigana: "けっか", meaning: "결과"),
//        JWordModel(kanji: "欠席", yomigana: "けっせき", meaning: "결석"),
//        JWordModel(kanji: "欠点", yomigana: "けってん", meaning: "결점"),
//        JWordModel(kanji: "決定", yomigana: "けってい", meaning: "결정"),
//        JWordModel(kanji: "決まる", yomigana: "きまる", meaning: "정해지다"),
//        JWordModel(kanji: "決める", yomigana: "きめる", meaning: "정하다"),
//        JWordModel(kanji: "気持ち", yomigana: "きもち", meaning: "기분"),
//        JWordModel(kanji: "気分", yomigana: "きぶん", meaning: "기분, 느낌"),
//        JWordModel(kanji: "希望", yomigana: "きぼう", meaning: "희망"),
//        JWordModel(kanji: "記憶", yomigana: "きおく", meaning: "기억"),
//        JWordModel(kanji: "記念", yomigana: "きねん", meaning: "기념"),
//        JWordModel(kanji: "記入", yomigana: "きにゅう", meaning: "기입"),
//        JWordModel(kanji: "記者", yomigana: "きしゃ", meaning: "기자"),
//        JWordModel(kanji: "技術", yomigana: "ぎじゅつ", meaning: "기술"),
//        JWordModel(kanji: "期待", yomigana: "きたい", meaning: "기대"),
//        JWordModel(kanji: "帰宅", yomigana: "きたく", meaning: "귀가"),
//        JWordModel(kanji: "北", yomigana: "きた", meaning: "북쪽"),
//        JWordModel(kanji: "汚い", yomigana: "きたない", meaning: "더럽다"),
//        JWordModel(kanji: "喫茶店", yomigana: "きっさてん", meaning: "다방, 커피숍"),
//        JWordModel(kanji: "切手", yomigana: "きって", meaning: "우표"),
//        JWordModel(kanji: "切符", yomigana: "きっぷ", meaning: "표, 티켓"),
//        JWordModel(kanji: "気温", yomigana: "きおん", meaning: "기온"),
//        JWordModel(kanji: "教科書", yomigana: "きょうかしょ", meaning: "교과서"),
//        JWordModel(kanji: "教会", yomigana: "きょうかい", meaning: "교회"),
//        JWordModel(kanji: "教師", yomigana: "きょうし", meaning: "교사"),
//        JWordModel(kanji: "教室", yomigana: "きょうしつ", meaning: "교실"),
//        JWordModel(kanji: "兄弟", yomigana: "きょうだい", meaning: "형제"),
//        JWordModel(kanji: "競争", yomigana: "きょうそう", meaning: "경쟁"),
//        JWordModel(kanji: "興味", yomigana: "きょうみ", meaning: "흥미"),
//        JWordModel(kanji: "協力", yomigana: "きょうりょく", meaning: "협력"),
//        JWordModel(kanji: "近所", yomigana: "きんじょ", meaning: "근처"),
//        JWordModel(kanji: "金", yomigana: "きん", meaning: "금, 돈"),
//        JWordModel(kanji: "金額", yomigana: "きんがく", meaning: "금액"),
//        JWordModel(kanji: "金庫", yomigana: "きんこ", meaning: "금고"),
//        JWordModel(kanji: "金曜日", yomigana: "きんようび", meaning: "금요일"),
//        JWordModel(kanji: "禁止", yomigana: "きんし", meaning: "금지"),
//        JWordModel(kanji: "近代", yomigana: "きんだい", meaning: "근대"),
//        JWordModel(kanji: "近道", yomigana: "ちかみち", meaning: "지름길"),
//        JWordModel(kanji: "近づく", yomigana: "ちかづく", meaning: "가까워지다"),
//        JWordModel(kanji: "近づける", yomigana: "ちかづける", meaning: "가까이하다"),
//        JWordModel(kanji: "近年", yomigana: "きんねん", meaning: "근년, 최근"),
//        JWordModel(kanji: "具合", yomigana: "ぐあい", meaning: "상태, 형편"),
//        JWordModel(kanji: "空気", yomigana: "くうき", meaning: "공기"),
//        JWordModel(kanji: "空港", yomigana: "くうこう", meaning: "공항"),
//        JWordModel(kanji: "草", yomigana: "くさ", meaning: "풀"),
//        JWordModel(kanji: "臭い", yomigana: "くさい", meaning: "냄새나다"),
//        JWordModel(kanji: "薬", yomigana: "くすり", meaning: "약"),
//        JWordModel(kanji: "下さる", yomigana: "くださる", meaning: "주시다JWordModel(존경)"),
//        JWordModel(kanji: "下りる", yomigana: "おりる", meaning: "내리다"),
//        JWordModel(kanji: "果物", yomigana: "くだもの", meaning: "과일"),
//        JWordModel(kanji: "口", yomigana: "くち", meaning: "입"),
//        JWordModel(kanji: "具体的", yomigana: "ぐたいてき", meaning: "구체적"),
//        JWordModel(kanji: "工夫", yomigana: "くふう", meaning: "궁리, 고안"),
//        JWordModel(kanji: "首", yomigana: "くび", meaning: "목"),
//        JWordModel(kanji: "雲", yomigana: "くも", meaning: "구름"),
//        JWordModel(kanji: "暗い", yomigana: "くらい", meaning: "어둡다"),
//        JWordModel(kanji: "暮らし", yomigana: "くらし", meaning: "생활"),
//        JWordModel(kanji: "暮らす", yomigana: "くらす", meaning: "살다, 생활하다"),
//        JWordModel(kanji: "比べる", yomigana: "くらべる", meaning: "비교하다"),
//        JWordModel(kanji: "クラス", yomigana: "クラス", meaning: "반, 클래스"),
//        JWordModel(kanji: "車", yomigana: "くるま", meaning: "자동차"),
//        JWordModel(kanji: "繰り返す", yomigana: "くりかえす", meaning: "반복하다"),
//        JWordModel(kanji: "苦しい", yomigana: "くるしい", meaning: "괴롭다, 힘들다"),
//        JWordModel(kanji: "苦しむ", yomigana: "くるしむ", meaning: "괴로워하다"),
//        JWordModel(kanji: "来る", yomigana: "くる", meaning: "오다"),
//        JWordModel(kanji: "訓練", yomigana: "くんれん", meaning: "훈련"),
//        JWordModel(kanji: "計画", yomigana: "けいかく", meaning: "계획"),
//        JWordModel(kanji: "警察", yomigana: "けいさつ", meaning: "경찰"),
//        JWordModel(kanji: "経済", yomigana: "けいざい", meaning: "경제"),
//        JWordModel(kanji: "景色", yomigana: "けしき", meaning: "경치"),
//        JWordModel(kanji: "決心", yomigana: "けっしん", meaning: "결심"),
//        JWordModel(kanji: "結論", yomigana: "けつろん", meaning: "결론"),
//        JWordModel(kanji: "下宿", yomigana: "げしゅく", meaning: "하숙"),
//        JWordModel(kanji: "下車", yomigana: "げしゃ", meaning: "하차"),
//        JWordModel(kanji: "化学", yomigana: "かがく", meaning: "화학"),
//        JWordModel(kanji: "化粧", yomigana: "けしょう", meaning: "화장"),
//        JWordModel(kanji: "現在", yomigana: "げんざい", meaning: "현재"),
//        JWordModel(kanji: "現実", yomigana: "げんじつ", meaning: "현실"),
//        JWordModel(kanji: "現象", yomigana: "げんしょう", meaning: "현상"),
//        JWordModel(kanji: "現場", yomigana: "げんば", meaning: "현장"),
//        JWordModel(kanji: "限界", yomigana: "げんかい", meaning: "한계"),
//        JWordModel(kanji: "言語", yomigana: "げんご", meaning: "언어"),
//        JWordModel(kanji: "原因", yomigana: "げんいん", meaning: "원인"),
//        JWordModel(kanji: "原則", yomigana: "げんそく", meaning: "원칙"),
//        JWordModel(kanji: "原料", yomigana: "げんりょう", meaning: "원료"),
//        JWordModel(kanji: "玄関", yomigana: "げんかん", meaning: "현관"),
//        JWordModel(kanji: "元気", yomigana: "げんき", meaning: "건강, 기운"),
//        JWordModel(kanji: "現金", yomigana: "げんきん", meaning: "현금"),
//        JWordModel(kanji: "原稿", yomigana: "げんこう", meaning: "원고"),
//        JWordModel(kanji: "原産", yomigana: "げんさん", meaning: "원산"),
//        JWordModel(kanji: "原爆", yomigana: "げんばく", meaning: "원자폭탄"),
//        JWordModel(kanji: "原発", yomigana: "げんぱつ", meaning: "원자력 발전소"),
//        JWordModel(kanji: "原油", yomigana: "げんゆ", meaning: "원유"),
//        JWordModel(kanji: "原作", yomigana: "げんさく", meaning: "원작"),
//        JWordModel(kanji: "原子", yomigana: "げんし", meaning: "원자"),
//        JWordModel(kanji: "原始", yomigana: "げんし", meaning: "원시"),
//        JWordModel(kanji: "原則", yomigana: "げんそく", meaning: "원칙"),
//        JWordModel(kanji: "原料", yomigana: "げんりょう", meaning: "원료"),
//        JWordModel(kanji: "原産", yomigana: "げんさん", meaning: "원산"),
//        JWordModel(kanji: "原爆", yomigana: "げんばく", meaning: "원자폭탄"),
//        JWordModel(kanji: "現象", yomigana: "げんしょう", meaning: "현상"),
//        JWordModel(kanji: "現場", yomigana: "げんば", meaning: "현장"),
//        JWordModel(kanji: "限界", yomigana: "げんかい", meaning: "한계"),
//        JWordModel(kanji: "言語", yomigana: "げんご", meaning: "언어"),
//        JWordModel(kanji: "原則", yomigana: "げんそく", meaning: "원칙"),
//        JWordModel(kanji: "原料", yomigana: "げんりょう", meaning: "원료"),
//        JWordModel(kanji: "玄関", yomigana: "げんかん", meaning: "현관"),
//        JWordModel(kanji: "元気", yomigana: "げんき", meaning: "건강, 기운"),
//        JWordModel(kanji: "現金", yomigana: "げんきん", meaning: "현금"),
//        JWordModel(kanji: "原稿", yomigana: "げんこう", meaning: "원고"),
//        JWordModel(kanji: "原産", yomigana: "げんさん", meaning: "원산"),
//        JWordModel(kanji: "原爆", yomigana: "げんばく", meaning: "원자폭탄"),
//        JWordModel(kanji: "原発", yomigana: "げんぱつ", meaning: "원자력 발전소"),
//        JWordModel(kanji: "原油", yomigana: "げんゆ", meaning: "원유"),
//        JWordModel(kanji: "原作", yomigana: "げんさく", meaning: "원작"),
//        JWordModel(kanji: "原子", yomigana: "げんし", meaning: "원자"),
//        JWordModel(kanji: "原始", yomigana: "げんし", meaning: "원시"),
//        JWordModel(kanji: "誤解", yomigana: "ごかい", meaning: "오해"),
//        JWordModel(kanji: "交換", yomigana: "こうかん", meaning: "교환"),
//        JWordModel(kanji: "公開", yomigana: "こうかい", meaning: "공개"),
//        JWordModel(kanji: "効果", yomigana: "こうか", meaning: "효과"),
//        JWordModel(kanji: "講義", yomigana: "こうぎ", meaning: "강의"),
//        JWordModel(kanji: "工業", yomigana: "こうぎょう", meaning: "공업"),
//        JWordModel(kanji: "郊外", yomigana: "こうがい", meaning: "교외"),
//        JWordModel(kanji: "合格", yomigana: "ごうかく", meaning: "합격"),
//        JWordModel(kanji: "広告", yomigana: "こうこく", meaning: "광고"),
//        JWordModel(kanji: "交際", yomigana: "こうさい", meaning: "교제"),
//        JWordModel(kanji: "高速", yomigana: "こうそく", meaning: "고속"),
//        JWordModel(kanji: "行動", yomigana: "こうどう", meaning: "행동"),
//        JWordModel(kanji: "交通", yomigana: "こうつう", meaning: "교통"),
//        JWordModel(kanji: "幸福", yomigana: "こうふく", meaning: "행복"),
//        JWordModel(kanji: "公平", yomigana: "こうへい", meaning: "공평"),
//        JWordModel(kanji: "後輩", yomigana: "こうはい", meaning: "후배"),
//        JWordModel(kanji: "効率", yomigana: "こうりつ", meaning: "효율"),
//        JWordModel(kanji: "国際", yomigana: "こくさい", meaning: "국제"),
//        JWordModel(kanji: "国籍", yomigana: "こくせき", meaning: "국적"),
//        JWordModel(kanji: "国民", yomigana: "こくみん", meaning: "국민"),
//        JWordModel(kanji: "故障", yomigana: "こしょう", meaning: "고장"),
//        JWordModel(kanji: "個人", yomigana: "こじん", meaning: "개인"),
//        JWordModel(kanji: "誤字", yomigana: "ごじ", meaning: "오자"),
//        JWordModel(kanji: "故郷", yomigana: "こきょう", meaning: "고향"),
//        JWordModel(kanji: "誤解", yomigana: "ごかい", meaning: "오해"),
//        JWordModel(kanji: "国会", yomigana: "こっかい", meaning: "국회"),
//        JWordModel(kanji: "骨", yomigana: "ほね", meaning: "뼈"),
//        JWordModel(kanji: "細い", yomigana: "ほそい", meaning: "가늘다"),
//        JWordModel(kanji: "保存", yomigana: "ほぞん", meaning: "보존"),
//        JWordModel(kanji: "保証", yomigana: "ほしょう", meaning: "보증"),
//        JWordModel(kanji: "方法", yomigana: "ほうほう", meaning: "방법"),
//        JWordModel(kanji: "訪問", yomigana: "ほうもん", meaning: "방문"),
//        JWordModel(kanji: "報告", yomigana: "ほうこく", meaning: "보고"),
//        JWordModel(kanji: "方向", yomigana: "ほうこう", meaning: "방향"),
//        JWordModel(kanji: "法律", yomigana: "ほうりつ", meaning: "법률"),
//        JWordModel(kanji: "本当", yomigana: "ほんとう", meaning: "정말, 사실"),
//        JWordModel(kanji: "翻訳", yomigana: "ほんやく", meaning: "번역"),
//        JWordModel(kanji: "毎週", yomigana: "まいしゅう", meaning: "매주"),
//        JWordModel(kanji: "毎月", yomigana: "まいつき", meaning: "매달"),
//        JWordModel(kanji: "毎年", yomigana: "まいとし", meaning: "매년"),
//        JWordModel(kanji: "毎晩", yomigana: "まいばん", meaning: "매일 밤"),
//        JWordModel(kanji: "負ける", yomigana: "まける", meaning: "지다"),
//        JWordModel(kanji: "真面目", yomigana: "まじめ", meaning: "성실함"),
//        JWordModel(kanji: "間違い", yomigana: "まちがい", meaning: "실수"),
//        JWordModel(kanji: "間に合う", yomigana: "まにあう", meaning: "시간에 맞다"),
//        JWordModel(kanji: "招待", yomigana: "しょうたい", meaning: "초대"),
//        JWordModel(kanji: "周囲", yomigana: "しゅうい", meaning: "주위"),
//        JWordModel(kanji: "種類", yomigana: "しゅるい", meaning: "종류"),
//        JWordModel(kanji: "修理", yomigana: "しゅうり", meaning: "수리"),
//        JWordModel(kanji: "集中", yomigana: "しゅうちゅう", meaning: "집중"),
//        JWordModel(kanji: "習慣", yomigana: "しゅうかん", meaning: "습관"),
//        JWordModel(kanji: "住所", yomigana: "じゅうしょ", meaning: "주소"),
//        JWordModel(kanji: "重要", yomigana: "じゅうよう", meaning: "중요"),
//        JWordModel(kanji: "授業", yomigana: "じゅぎょう", meaning: "수업"),
//        JWordModel(kanji: "受験", yomigana: "じゅけん", meaning: "수험"),
//        JWordModel(kanji: "受信", yomigana: "じゅしん", meaning: "수신"),
//        JWordModel(kanji: "受賞", yomigana: "じゅしょう", meaning: "수상"),
//        JWordModel(kanji: "受け付け", yomigana: "うけつけ", meaning: "접수"),
//        JWordModel(kanji: "受け取る", yomigana: "うけとる", meaning: "받다"),
//        JWordModel(kanji: "授与", yomigana: "じゅよ", meaning: "수여"),
//        JWordModel(kanji: "順番", yomigana: "じゅんばん", meaning: "순서"),
//        JWordModel(kanji: "準備", yomigana: "じゅんび", meaning: "준비"),
//        JWordModel(kanji: "助ける", yomigana: "たすける", meaning: "돕다"),
//        JWordModel(kanji: "詳細", yomigana: "しょうさい", meaning: "상세"),
//        JWordModel(kanji: "障害", yomigana: "しょうがい", meaning: "장애"),
//        JWordModel(kanji: "条件", yomigana: "じょうけん", meaning: "조건"),
//        JWordModel(kanji: "情報", yomigana: "じょうほう", meaning: "정보"),
//        JWordModel(kanji: "状況", yomigana: "じょうきょう", meaning: "상황"),
//        JWordModel(kanji: "状態", yomigana: "じょうたい", meaning: "상태"),
//        JWordModel(kanji: "常識", yomigana: "じょうしき", meaning: "상식"),
//        JWordModel(kanji: "上手", yomigana: "じょうず", meaning: "능숙함"),
//        JWordModel(kanji: "乗車", yomigana: "じょうしゃ", meaning: "승차"),
//        JWordModel(kanji: "乗客", yomigana: "じょうきゃく", meaning: "승객"),
//        JWordModel(kanji: "植物", yomigana: "しょくぶつ", meaning: "식물"),
//        JWordModel(kanji: "食事", yomigana: "しょくじ", meaning: "식사"),
//        JWordModel(kanji: "食堂", yomigana: "しょくどう", meaning: "식당"),
//        JWordModel(kanji: "食料品", yomigana: "しょくりょうひん", meaning: "식료품"),
//        JWordModel(kanji: "信号", yomigana: "しんごう", meaning: "신호"),
//        JWordModel(kanji: "信頼", yomigana: "しんらい", meaning: "신뢰"),
//        JWordModel(kanji: "親切", yomigana: "しんせつ", meaning: "친절함"),
//        JWordModel(kanji: "親友", yomigana: "しんゆう", meaning: "친구, 절친"),
//        JWordModel(kanji: "進学", yomigana: "しんがく", meaning: "진학"),
//        JWordModel(kanji: "進歩", yomigana: "しんぽ", meaning: "진보"),
//        JWordModel(kanji: "進路", yomigana: "しんろ", meaning: "진로"),
//        JWordModel(kanji: "新鮮", yomigana: "しんせん", meaning: "신선함"),
//        JWordModel(kanji: "深刻", yomigana: "しんこく", meaning: "심각함"),
//        JWordModel(kanji: "深夜", yomigana: "しんや", meaning: "심야"),
//        JWordModel(kanji: "信号", yomigana: "しんごう", meaning: "신호"),
//        JWordModel(kanji: "信用", yomigana: "しんよう", meaning: "신용"),
//        JWordModel(kanji: "信号機", yomigana: "しんごうき", meaning: "신호등"),
//        JWordModel(kanji: "人間", yomigana: "にんげん", meaning: "인간"),
//        JWordModel(kanji: "人気", yomigana: "にんき", meaning: "인기"),
//        JWordModel(kanji: "人数", yomigana: "にんずう", meaning: "인원수"),
//        JWordModel(kanji: "入学", yomigana: "にゅうがく", meaning: "입학"),
//        JWordModel(kanji: "入場", yomigana: "にゅうじょう", meaning: "입장"),
//        JWordModel(kanji: "入院", yomigana: "にゅういん", meaning: "입원"),
//        JWordModel(kanji: "入国", yomigana: "にゅうこく", meaning: "입국"),
//        JWordModel(kanji: "入金", yomigana: "にゅうきん", meaning: "입금"),
//        JWordModel(kanji: "入社", yomigana: "にゅうしゃ", meaning: "입사"),
//        JWordModel(kanji: "入手", yomigana: "にゅうしゅ", meaning: "입수"),
//        JWordModel(kanji: "入選", yomigana: "にゅうせん", meaning: "입선"),
//        JWordModel(kanji: "入力", yomigana: "にゅうりょく", meaning: "입력"),
//        JWordModel(kanji: "入門", yomigana: "にゅうもん", meaning: "입문"),
//        JWordModel(kanji: "農業", yomigana: "のうぎょう", meaning: "농업"),
//        JWordModel(kanji: "農家", yomigana: "のうか", meaning: "농가"),
//        JWordModel(kanji: "農民", yomigana: "のうみん", meaning: "농민"),
//        JWordModel(kanji: "能力", yomigana: "のうりょく", meaning: "능력"),
//        JWordModel(kanji: "発見", yomigana: "はっけん", meaning: "발견"),
//        JWordModel(kanji: "発行", yomigana: "はっこう", meaning: "발행"),
//        JWordModel(kanji: "発車", yomigana: "はっしゃ", meaning: "출발JWordModel(차량)"),
//        JWordModel(kanji: "発展", yomigana: "はってん", meaning: "발전"),
//        JWordModel(kanji: "発表", yomigana: "はっぴょう", meaning: "발표"),
//        JWordModel(kanji: "発明", yomigana: "はつめい", meaning: "발명"),
//        JWordModel(kanji: "発売", yomigana: "はつばい", meaning: "발매"),
//        JWordModel(kanji: "発音", yomigana: "はつおん", meaning: "발음"),
//        JWordModel(kanji: "反対", yomigana: "はんたい", meaning: "반대"),
//        JWordModel(kanji: "反発", yomigana: "はんぱつ", meaning: "반발"),
//        JWordModel(kanji: "販売", yomigana: "はんばい", meaning: "판매"),
//        JWordModel(kanji: "犯罪", yomigana: "はんざい", meaning: "범죄"),
//        JWordModel(kanji: "必死", yomigana: "ひっし", meaning: "필사적"),
//        JWordModel(kanji: "必要", yomigana: "ひつよう", meaning: "필요"),
//        JWordModel(kanji: "比較", yomigana: "ひかく", meaning: "비교"),
//        JWordModel(kanji: "被害", yomigana: "ひがい", meaning: "피해"),
//        JWordModel(kanji: "悲劇", yomigana: "ひげき", meaning: "비극"),
//        JWordModel(kanji: "非常", yomigana: "ひじょう", meaning: "비상"),
//        JWordModel(kanji: "美術", yomigana: "びじゅつ", meaning: "미술"),
//        JWordModel(kanji: "美人", yomigana: "びじん", meaning: "미인"),
//        JWordModel(kanji: "美容", yomigana: "びよう", meaning: "미용"),
//        JWordModel(kanji: "表現", yomigana: "ひょうげん", meaning: "표현"),
//        JWordModel(kanji: "表情", yomigana: "ひょうじょう", meaning: "표정"),
//        JWordModel(kanji: "表紙", yomigana: "ひょうし", meaning: "표지"),
//        JWordModel(kanji: "評価", yomigana: "ひょうか", meaning: "평가"),
//        JWordModel(kanji: "病院", yomigana: "びょういん", meaning: "병원"),
//        JWordModel(kanji: "病気", yomigana: "びょうき", meaning: "병"),
//        JWordModel(kanji: "品物", yomigana: "しなもの", meaning: "물건"),
//        JWordModel(kanji: "不安", yomigana: "ふあん", meaning: "불안"),
//        JWordModel(kanji: "不便", yomigana: "ふべん", meaning: "불편"),
//        JWordModel(kanji: "不足", yomigana: "ふそく", meaning: "부족"),
//        JWordModel(kanji: "普通", yomigana: "ふつう", meaning: "보통"),
//        JWordModel(kanji: "夫婦", yomigana: "ふうふ", meaning: "부부"),
//        JWordModel(kanji: "部分", yomigana: "ぶぶん", meaning: "부분"),
//        JWordModel(kanji: "部長", yomigana: "ぶちょう", meaning: "부장"),
//        JWordModel(kanji: "文化", yomigana: "ぶんか", meaning: "문화"),
//        JWordModel(kanji: "文学", yomigana: "ぶんがく", meaning: "문학"),
//        JWordModel(kanji: "文章", yomigana: "ぶんしょう", meaning: "문장"),
//        JWordModel(kanji: "分析", yomigana: "ぶんせき", meaning: "분석"),
//        JWordModel(kanji: "分野", yomigana: "ぶんや", meaning: "분야"),
//        JWordModel(kanji: "平和", yomigana: "へいわ", meaning: "평화"),
//        JWordModel(kanji: "平均", yomigana: "へいきん", meaning: "평균"),
//        JWordModel(kanji: "返事", yomigana: "へんじ", meaning: "대답, 답장"),
//        JWordModel(kanji: "変更", yomigana: "へんこう", meaning: "변경"),
//        JWordModel(kanji: "返信", yomigana: "へんしん", meaning: "회신"),
//        JWordModel(kanji: "変化", yomigana: "へんか", meaning: "변화"),
//        JWordModel(kanji: "便利", yomigana: "べんり", meaning: "편리"),
//        JWordModel(kanji: "貿易", yomigana: "ぼうえき", meaning: "무역"),
//        JWordModel(kanji: "防止", yomigana: "ぼうし", meaning: "방지"),
//        JWordModel(kanji: "方法", yomigana: "ほうほう", meaning: "방법"),
//        JWordModel(kanji: "訪問", yomigana: "ほうもん", meaning: "방문"),
//        JWordModel(kanji: "報告", yomigana: "ほうこく", meaning: "보고"),
//        JWordModel(kanji: "方向", yomigana: "ほうこう", meaning: "방향"),
//        JWordModel(kanji: "法律", yomigana: "ほうりつ", meaning: "법률"),
//        JWordModel(kanji: "本当", yomigana: "ほんとう", meaning: "정말, 사실"),
//        JWordModel(kanji: "翻訳", yomigana: "ほんやく", meaning: "번역"),
//        JWordModel(kanji: "毎週", yomigana: "まいしゅう", meaning: "매주"),
//        JWordModel(kanji: "毎月", yomigana: "まいつき", meaning: "매달"),
//        JWordModel(kanji: "毎年", yomigana: "まいとし", meaning: "매년"),
//        JWordModel(kanji: "毎晩", yomigana: "まいばん", meaning: "매일 밤"),
//        JWordModel(kanji: "負ける", yomigana: "まける", meaning: "지다"),
//        JWordModel(kanji: "真面目", yomigana: "まじめ", meaning: "성실함"),
//        JWordModel(kanji: "間違い", yomigana: "まちがい", meaning: "실수"),
//        JWordModel(kanji: "間に合う", yomigana: "まにあう", meaning: "시간에 맞다"),
//        JWordModel(kanji: "招待", yomigana: "しょうたい", meaning: "초대"),
//        JWordModel(kanji: "周囲", yomigana: "しゅうい", meaning: "주위")
//    ]
//}
